from subject_app.models import Programme, Board
from register_app.edusystem import QualificationType as QT 
from register_app.edusystem import GradingScale as GS
from register_app.edusystem import ExamSeries as ES
from register_app.edusystem import SubjectGroup as SG
from register_app.edusystem import MarkType as MT

SUBJECTS = [
    {
        'name': (
            'ART & DESIGN: Art, Craft & Design',
            'ART & DESIGN: Fine Art',
            'ART & DESIGN: Graphic Communication',
            'ART & DESIGN: Textile design',
            'ART & DESIGN: 3D design',
            'ART & DESIGN: Photography',
            ),
        'code': (
            '9AD0',
            '9FA0',
            '9GC0',
            '9TE0',
            '9TD0',
            '9PY0',
        ),
        'group': SG.British.PROFESSIONAL,
        'qualification': QT.British.A2,
        'programme': Programme.British.ALEVEL,
        'board': Board.EDEXCEL,
        'first_assessment': 2017,
        'mark': 180,
        'mark_type': MT.SCALED,
        'grading': GS.ALevel.SINGLE_ASE, 
        'series': [ES.JUNE],
        'modular': False,
        'components': [
            {
                'name': 'Component 1 (NEA): Personal investigation',
                'code': '*/01',
                'mark': 90,
                'weighting': 60,
                'duration': '',
                'grading': GS.ALevel.SINGLE_ASE,
                'internal': True,
            },
            {
                'name': 'Component 2: Externally set assignment',
                'code': '*/02',
                'mark': 72,
                'weighting': 40,
                'duration': 'Prep. period + 15 hours',
                'grading': GS.ALevel.SINGLE_ASE,
                'internal': True,
            },
            
        ]
    },
    {
        'name': 'SPANISH',
        'code': '9SP0',
        'group': SG.British.LANGUAGES,
        'qualification': QT.British.A2,
        'programme': Programme.British.ALEVEL,
        'board': Board.EDEXCEL,
        'first_assessment': 2018,
        'mark': 400,
        'grading': GS.ALevel.SINGLE_ASE, 
        'series': [ES.JUNE],
        'modular': False,
        'components': [
            {
                'name': 'Paper 1: Listening, reading and translation',
                'code': '*/01',
                'mark': 80,
                'weighting': 40,
                'duration': '2 hours',
                'grading': GS.ALevel.SINGLE_ASE,
                'internal': False,
            },
            {
                'name': 'Paper 2: Written response to works and translation',
                'code': '*/02',
                'mark': 120,
                'weighting': 30,
                'duration': '2 hours',
                'grading': GS.ALevel.SINGLE_ASE,
                'internal': False,
            },
            {
                'name': 'Paper 3: Speaking',
                'code': '*/03',
                'mark': 72,
                'weighting': 30,
                'duration': '21-23 minutes',
                'grading': GS.ALevel.SINGLE_ASE,
                'internal': False,
            },
            
        ]
    },
     {
        'name': 'FURTHER MATHEMATICS',
        'code': '9FM0',
        'group': SG.British.MATHS,
        'qualification': QT.British.AS,
        'programme': Programme.British.ALEVEL,
        'board': Board.EDEXCEL,
        'first_assessment': 2018,
        'mark': 300,
        'grading': GS.ALevel.SINGLE_ASE, 
        'series': [ES.JUNE],
        'modular': False,
        'components': [
            {
                'name': 'Paper 1: Core Pure Mathematics 1',
                'code': '*/01',
                'mark': 75,
                'weighting': 25,
                'duration': '1 hour 30 minutes',
                'grading': GS.ALevel.SINGLE_ASE,
                'internal': False,
            },
            {
                'name': 'Paper 2: Core Pure Mathematics 2',
                'code': '*/02',
                'mark': 75,
                'weighting': 25,
                'duration': '1 hour 30 minutes',
                'grading': GS.ALevel.SINGLE_ASE,
                'internal': False,
            },
            {
                'name': 'Paper 3A: Further Pure Mathematics 1',
                'code': '*/3A',
                'mark': 75,
                'weighting': 25,
                'duration': '1 hour 30 minutes',
                'grading': GS.ALevel.SINGLE_ASE,
                'internal': False,
            },
           {
                'name': 'Paper 3B: Further Statistics 1',
                'code': '*/3B',
                'mark': 75,
                'weighting': 25,
                'duration': '1 hour 30 minutes',
                'grading': GS.ALevel.SINGLE_ASE,
                'internal': False,
            },
            {
                'name': 'Paper 3C: Further Mechanics 1',
                'code': '*/3C',
                'mark': 75,
                'weighting': 25,
                'duration': '1 hour 30 minutes',
                'grading': GS.ALevel.SINGLE_ASE,
                'internal': False,
            },
            {
                'name': 'Paper 3D: Decision Mathematics 1',
                'code': '*/3D',
                'mark': 75,
                'weighting': 25,
                'duration': '1 hour 30 minutes',
                'grading': GS.ALevel.SINGLE_ASE,
                'internal': False,
            },
            {
                'name': 'Paper 4A: Further Pure Mathematics 2',
                'code': '*/4A',
                'mark': 75,
                'weighting': 25,
                'duration': '1 hour 30 minutes',
                'grading': GS.ALevel.SINGLE_ASE,
                'internal': False,
            },
            {
                'name': 'Paper 4B: Further Statistics 2',
                'code': '*/4B',
                'mark': 75,
                'weighting': 25,
                'duration': '1 hour 30 minutes',
                'grading': GS.ALevel.SINGLE_ASE,
                'internal': False,
            },
            {
                'name': 'Paper 4C: Further Mechanics 2',
                'code': '*/4C',
                'mark': 75,
                'weighting': 25,
                'duration': '1 hour 30 minutes',
                'grading': GS.ALevel.SINGLE_ASE,
                'internal': False,
            },
            {
                'name': 'Paper 4D: Decision Mathemmatics 2',
                'code': '*/4D',
                'mark': 75,
                'weighting': 25,
                'duration': '1 hour 30 minutes',
                'grading': GS.ALevel.SINGLE_ASE,
                'internal': False,
            },
            
        ]
    }
]