from choices import QT, GS, Ser, SG, MT

QUALIFICATIONS = [
    {
        'subject': 'Further Mathematics',
        'code': '8FM0',
        'group': SG.UK.MATHS,
        'name': QT.UKN.Edexcel.AL.AS,
        'glh': 180,
        'first_assessment': 2017,
        'mark': 160,
        'mark_type': MT.SCALED,
        'grading': GS.AL.SINGLE_AE, 
        'series': [Ser.Exam.JUN],
        'modular': False,
        'components': [
            {
                'name': 'Paper 1: Core Pure Mathematics',
                'code': '8FM0/01',
                'mark': 80,
                'mark_type': MT.RAW,
                'weighting': '50%',
                'duration': '1 hour 40 minutes',
                'grading': GS.AL.SINGLE_AE,
                'internal': False,
                'optional': False,
            },
            {
                'name': 'Paper 21: Further Pure Mathematics 1',
                'code': '8FM0/21',
                'mark': 40,
                'mark_type': MT.RAW,
                'weighting': '25%',
                'duration': '50 minutes',
                'grading': GS.AL.SINGLE_AE,
                'internal': False,
                'optional': True,
            },
            {
                'name': 'Paper 22: Further Pure Mathematics 2',
                'code': '8FM0/22',
                'mark': 40,
                'mark_type': MT.RAW,
                'weighting': '25%',
                'duration': '50 minutes (*)',
                'grading': GS.AL.SINGLE_AE,
                'internal': False,
                'optional': True,
            },
            {
                'name': 'Paper 23: Further Statistics 1',
                'code': '8FM0/23',
                'mark': 40,
                'mark_type': MT.RAW,
                'weighting': '25%',
                'duration': '50 minutes (*)',
                'grading': GS.AL.SINGLE_AE,
                'internal': False,
                'optional': True,
            },
            {
                'name': 'Paper 24: Further Statistics 2',
                'code': '8FM0/24',
                'mark': 40,
                'mark_type': MT.RAW,
                'weighting': '25%',
                'duration': '50 minutes (*)',
                'grading': GS.AL.SINGLE_AE,
                'internal': False,
                'optional': True,
            },
            {
                'name': 'Paper 25: Further Mechanics 1',
                'code': '8FM0/25',
                'mark': 40,
                'mark_type': MT.RAW,
                'weighting': '25%',
                'duration': '50 minutes (*)',
                'grading': GS.AL.SINGLE_AE,
                'internal': False,
                'optional': True,
            },
            {
                'name': 'Paper 26: Further Mechanics 2',
                'code': '8FM0/26',
                'mark': 40,
                'mark_type': MT.RAW,
                'weighting': '25%',
                'duration': '50 minutes (*)',
                'grading': GS.AL.SINGLE_AE,
                'internal': False,
                'optional': True,
            },
            {
                'name': 'Paper 27: Decision Mathematics 1',
                'code': '8FM0/27',
                'mark': 40,
                'mark_type': MT.RAW,
                'weighting': '25%',
                'duration': '50 minutes (*)',
                'grading': GS.AL.SINGLE_AE,
                'internal': False,
                'optional': True,
            },
            {
                'name': 'Paper 28: Decision Mathematics 2',
                'code': '8FM0/28',
                'mark': 40,
                'mark_type': MT.RAW,
                'weighting': '25%',
                'duration': '50 minutes (*)',
                'grading': GS.AL.SINGLE_AE,
                'internal': False,
                'optional': True,
            },
            
        ]
    },
]