from choices import QK, QT, GS, Ser, SG, MT, Board

SUBJECTS = [
    {
        'subject': 'Biology',
        'code': 'XBI11',
        'group': SG.UK.SCIENCES,
        'name': QT.UKI.Edexcel.IAL.AS,
        'glh': 180,
        'first_assessment': 2019,
        'last_assessment': None,
        'current': True,
        'mark': 300,
        'mark_type': MT.UMS,
        'grading': GS.AL.SINGLE_AE, 
        'series': [Ser.Exam.JAN, Ser.Exam.JUN, Ser.Exam.OCT],
        'modular': True, 
        'sub_qualification': None,
        'components': [
            {
                'name': 'Unit 1: Molecules, Diet, Transport and Health',
                'code': 'WBI11/01',
                'mark': 80,
                'mark_adjusted': 120,
                'mark_adjusted_type': MT.UMS,
                'weighting': '40 % of IAS, 20 % of IAL',
                'duration': '1 hour 30 minutes',
                'grading': GS.AL.SINGLE_AE,
                'internal': False,
            },
            {
                'name': 'Unit 2: Cells, Development, Biodiversity and Conservation',
                'code': 'WBI12/01',
                'mark': 80,
                'mark_adjusted': 120,
                'mark_adjusted_type': MT.UMS,
                'weighting': '40 % of IAS, 20 % of IAL',
                'duration': '1 hour 30 miinutes',
                'grading': GS.AL.SINGLE_AE,
                'internal': False,
            },
            {
                'name': 'Unit 3: Practical Skills in Biology I',
                'code': 'WBI13/01',
                'mark': 50,
                'mark_adjusted': 60,
                'mark_adjusted_type': MT.UMS,
                'weighting': '20 % of IAS, 10 % of IAL', 
                'duration': '1 hour 20 minutes',
                'grading': GS.AL.SINGLE_AE,
                'internal': False,
            },
        ]
    },
    {
        'subject': 'Biology',
        'code': 'YBI11',
        'group': SG.UK.SCIENCES,
        'name': QT.UKI.Edexcel.IAL.A2,
        'glh': 360,
        'first_assessment': 2019,
        'last_assessment': None,
        'current': True,
        'mark': 600,
        'mark_type': MT.UMS,
        'grading': (GS.AL.SINGLE_AE, GS.AL.SINGLE_ASE), 
        'series': [Ser.Exam.JAN, Ser.Exam.JUN, Ser.Exam.OCT],
        'modular': True, 
        'sub_qualification': {
            'name': QT.UKI.Edexcel.IAL.AS,
            'code': 'XBI11',
            'first_assessment': 2019,
        },
        'components': [
            {
                'name': 'Unit 4: Energy, Environment, Microbiology and Immunity',
                'code': 'WBI14/01',
                'mark': 90,
                'mark_adjusted': 120,
                'mark_adjusted_type': MT.UMS,
                'weighting':  '40 % of IA2, 20 % of IAL',
                'duration': '1 hour 45 minutes',
                'grading': GS.AL.SINGLE_ASE,
                'internal': False,
            },
            {
                'name': 'Unit 5: Respiration, Internal Environment, Coordination and Gene Technology',
                'code': 'WBI15/01',
                'mark': 90,
                'mark_adjusted': 120,
                'mark_adjusted_type': MT.UMS,
                'weighting': '40 % of IA2, 20 % of IAL',
                'duration': '1 hour 45 minutes',
                'grading': GS.AL.SINGLE_ASE,
                'internal': False,
            },
            {
                'name': 'Unit 6: Practical Skills in Biology II',
                'code': 'WBI16/01',
                'mark': 50,
                'mark_adjusted': 60,
                'mark_adjusted_type': MT.UMS,
                'weighting': '20 % of IA2, 10% of IAL',
                'duration': '1 hour 20 minutes',
                'grading': GS.AL.SINGLE_ASE,
                'internal': False,
            }
        ]
    },
    {
        'subject': 'Business',
        'code': 'XBS11',
        'group': SG.UK.HUMANITIES,
        'name': QT.UKI.Edexcel.IAL.AS,
        'glh': 180,
        'first_assessment': 2019,
        'last_assessment': None,
        'current': True,
        'mark': 200,
        'mark_type': MT.UMS,
        'grading': GS.AL.SINGLE_AE, 
        'series': [Ser.Exam.JAN, Ser.Exam.JUN, Ser.Exam.OCT],
        'modular': True, 
        'sub_qualification': None,
        'components': [
            {
                'name': 'Unit 1: Marketing and People',
                'code': 'WBS11/01',
                'mark': 80,
                'mark_adjusted': 100,
                'mark_adjusted_type': MT.UMS,
                'weighting': '50 % of IAS, 25 % of IAL',
                'duration': '2 hours',
                'grading': GS.AL.SINGLE_AE,
                'internal': False,
            },
            {
                'name': 'Unit 2: Managing Business Activities',
                'code': 'WBS12/01',
                'mark': 80,
                'mark_adjusted': 100,
                'mark_adjusted_type': MT.UMS,
                'weighting': '50 % of IAS, 25 % of IAL',
                'duration': '2 hours',
                'grading': GS.AL.SINGLE_AE,
                'internal': False,
            },
        ]
    },
    {
        'subject': 'Business',
        'code': 'YBS11',
        'group': SG.UK.HUMANITIES,
        'name': QT.UKI.Edexcel.IAL.A2,
        'glh': 360,
        'first_assessment': 2019,
        'last_assessment': None,
        'current': True,
        'mark': 400,
        'mark_type': MT.UMS,
        'grading': (GS.AL.SINGLE_AE, GS.AL.SINGLE_ASE), 
        'series': [Ser.Exam.JAN, Ser.Exam.JUN, Ser.Exam.OCT],
        'modular': True, 
        'sub_qualification': {
            'name': QT.UKI.Edexcel.IAL.AS,
            'code': 'XBS11',
            'first_assessment': 2019,
        },
        'components': [
            {
                'name': 'Unit 3: Business Decisions And Strategy',
                'code': 'WBI14/01',
                'mark': 80,
                'mark_adjusted': 100,
                'mark_adjusted_type': MT.UMS,
                'weighting':  '50 % of IA2, 25 % of IAL',
                'duration': '2 hours',
                'grading': GS.AL.SINGLE_ASE,
                'internal': False,
            },
            {
                'name': 'Unit 4: Global Business',
                'code': 'WBI15/01',
                'mark': 80,
                'mark_adjusted': 100,
                'mark_adjusted_type': MT.UMS,
                'weighting': '50 % of IA2, 25 % of IAL',
                'duration': '2 hours',
                'grading': GS.AL.SINGLE_ASE,
                'internal': False,
            },
        ]
    },
    {
        'subject': 'Chemistry',
        'code': 'XCH11',
        'group': SG.UK.SCIENCES,
        'name': QT.UKI.Edexcel.IAL.AS,
        'glh': 180,
        'first_assessment': 2019,
        'last_assessment': None,
        'current': True,
        'mark': 300,
        'mark_type': MT.UMS,
        'grading': GS.AL.SINGLE_AE, 
        'series': [Ser.Exam.JAN, Ser.Exam.JUN, Ser.Exam.OCT],
        'modular': True, 
        'sub_qualification': None,
        'components': [
            {
                'name': 'Unit 1: Structure, Bonding and Introduction to Organic Chemistry',
                'code': 'WCH11/01',
                'mark': 80,
                'mark_adjusted': 120,
                'mark_adjusted_type': MT.UMS,
                'weighting': '40 % of IAS, 20 % of IAL',
                'duration': '1 hour 30 minutes',
                'grading': GS.AL.SINGLE_AE,
                'internal': False,
            },
            {
                'name': 'Unit 2: Energetics, Group Chemistry, Haloenoalkanes and Alcohol',
                'code': 'WCH12/01',
                'mark': 80,
                'mark_adjusted': 120,
                'mark_adjusted_type': MT.UMS,
                'weighting': '20 % of IAS, 10 % of IAL',
                'duration': '1 hour 30 miinutes',
                'grading': GS.AL.SINGLE_AE,
                'internal': False,
            },
            {
                'name': 'Unit 3: Practical Skills in Biology I',
                'code': 'WCH13/01',
                'mark': 50,
                'mark_adjusted': 60,
                'mark_adjusted_type': MT.UMS,
                'weighting': '20 % of IAS, 10 % of IAL', 
                'duration': '1 hour 20 minutes',
                'grading': GS.AL.SINGLE_AE,
                'internal': False,
            },
        ]
    },
    {
        'subject': 'Chemistry',
        'code': 'YCH11',
        'group': SG.UK.SCIENCES,
        'name': QT.UKI.Edexcel.IAL.A2,
        'glh': 360,
        'first_assessment': 2019,
        'last_assessment': None,
        'current': True,
        'mark': 600,
        'mark_type': MT.UMS,
        'grading': (GS.AL.SINGLE_AE, GS.AL.SINGLE_ASE), 
        'series': [Ser.Exam.JAN, Ser.Exam.JUN, Ser.Exam.OCT],
        'modular': True, 
        'sub_qualification': {
            'name': QT.UKI.Edexcel.IAL.AS,
            'code': 'XCH11',
            'first_assessment': 2019,
        },
        'components': [
            {
                'name': 'Unit 4: Rates, Equilibria and Further Organic Chemistry',
                'code': 'WBI14/01',
                'mark': 90,
                'mark_adjusted': 120,
                'mark_adjusted_type': MT.UMS,
                'weighting':  '40 % of IA2, 20 % of IAL',
                'duration': '1 hour 45 minutes',
                'grading': GS.AL.SINGLE_ASE,
                'internal': False,
            },
            {
                'name': 'Unit 5: Transition Metals and Organic Nitrogen Chemistry',
                'code': 'WBI15/01',
                'mark': 90,
                'mark_adjusted': 120,
                'mark_adjusted_type': MT.UMS,
                'weighting': '40 % of IA2, 20 % of IAL',
                'duration': '1 hour 45 minutes',
                'grading': GS.AL.SINGLE_ASE,
                'internal': False,
            },
            {
                'name': 'Unit 6: Practical Skills in Chemistry II',
                'code': 'WBI16/01',
                'mark': 50,
                'mark_adjusted': 60,
                'mark_adjusted_type': MT.UMS,
                'weighting': '20 % of IA2, 10% of IAL',
                'duration': '1 hour 20 minutes',
                'grading': GS.AL.SINGLE_ASE,
                'internal': False,
            }
        ]
    },
    {
        'subject': (
            'Mathematics', 'Mathematics',
            'Further Mathematics', 'Further Mathematics',
            'Pure Mathematics', 'Pure Mathematics',
        ),
                 
        'code': (
            'XMA01', 'YMA01',
            'XFM01', 'YFM01',
            'XPM01', 'YPM01',
        ),
        'name': (
            QT.UKI.Edexcel.IAL.AS, QT.UKI.Edexcel.IAL.A2, 
            QT.UKI.Edexcel.IAL.AS, QT.UKI.Edexcel.IAL.A2, 
            QT.UKI.Edexcel.IAL.AS, QT.UKI.Edexcel.IAL.A2, 
        ),
        'group': SG.UK.MATHS,
        'glh': (180, 360, 180, 360, 180, 360),
        'first_assessment': 2019,
        'mark': (300, 600, 300, 600, 300, 600),
        'mark_type': MT.UMS,
        'grading': (
            GS.AL.SINGLE_AE, 
            GS.AL.SINGLE_ASE,
            GS.AL.SINGLE_AE, 
            GS.AL.SINGLE_ASE,
            GS.AL.SINGLE_AE, 
            GS.AL.SINGLE_ASE,
            ), 
        'series': [Ser.Exam.JAN, Ser.Exam.JUN, Ser.Exam.OCT],
        'modular': True,
        'sub_qualification': (
            None,
            {
                'name': QT.UKI.Edexcel.IAL.AS,
                'code': 'XMA01',
                'first_assessment': 2019,
            },
            None,
            {
                'name': QT.UKI.Edexcel.IAL.AS,
                'code': 'XFM01',
                'first_assessment': 2019,
            },
            None,
            {
                'name': QT.UKI.Edexcel.IAL.AS,
                'code': 'XPM01',
                'first_assessment': 2019,
            },
        ),
        'components': [
            {
                'name': 'P1: Pure Mathematics 1',
                'code': 'WMA11/01',
                'mark': 75,
                'mark_adjusted': 100,
                'mark_adjusted_type': MT.UMS,
                'weighting': (
                    '33⅓ % of IAS, 16⅔ % of IAL', None,
                    None, None,
                    '33⅓ % of IAS, 16⅔ % of IAL', None,
                ),
                'duration': '1 hour 30 minutes',
                'grading': GS.AL.SINGLE_AE,
                'internal': False,
                'optional': False,
            },
            {
                'name': 'P2: Pure Mathematics 2',
                'code': 'WMA12/01',
                'mark': 75,
                'mark_adjusted': 100,
                'mark_adjusted_type': MT.UMS,
                'weighting': (
                    '33⅓ % of IAS, 16⅔ % of IAL', None,
                    None, None,
                    '33⅓ % of IAS, 16⅔ % of IAL', None,
                ),
                'duration': '1 hour 30 minutes',
                'grading': GS.AL.SINGLE_AE,
                'internal': False,
                'optional': False,
            },
            {
                'name': 'P3: Pure Mathematics 3',
                'code': 'WMA13/01',
                'mark': 75,
                'mark_adjusted': 100,
                'mark_adjusted_type': MT.UMS,
                'weighting': (
                    None, '33⅓ % of IAS, 16⅔ % of IAL',
                    None, None,
                    None, '33⅓ % of IAS, 16⅔ % of IAL',
                ),
                'duration': '1 hour 30 minutes',
                'grading': GS.AL.SINGLE_ASE,
                'internal': False,
                'optional': False,
            },
            {
                'name': 'P4: Pure Mathematics 4',
                'code': 'WMA14/01',
                'mark': 75,
                'mark_adjusted': 100,
                'mark_adjusted_type': MT.UMS,
                'weighting': (
                    None, '33⅓ % of IAS, 16⅔ % of IAL',
                    None, None,
                    None, '33⅓ % of IAS, 16⅔ % of IAL',
                ),
                'duration': '1 hour 30 minutes',
                'grading': GS.AL.SINGLE_ASE,
                'internal': False,
                'optional': False,
            },


            {
                'name': 'D1: Decision Mathematics 1',
                'code': 'WDM11/01',
                'mark': 75,
                'mark_adjusted': 100,
                'mark_adjusted_type': MT.UMS,
                'weighting': (
                    '33⅓ % of IAS, 16⅔ % of IAL', '33⅓ % of IA2, 16⅔ % of IAL',
                    '33⅓ % of IAS, 16⅔ % of IAL', '33⅓ % of IA2, 16⅔ % of IAL',
                    None, None,
                ),
                'duration': '1 hour 30 minutes',
                'grading': GS.AL.SINGLE_AE,
                'internal': False,
                'optional': True,
                'series': [Ser.Exam.JAN, Ser.Exam.JUN],
            },
            {
                'name': 'M1: Mechanics 1',
                'code': 'WME01',
                'mark': 75,
                'mark_adjusted': 100,
                'mark_adjusted_type': MT.UMS,
                'weighting': (
                    '33⅓ % of IAS, 16⅔ % of IAL', '33⅓ % of IA2, 16⅔ % of IAL',
                    '33⅓ % of IAS, 16⅔ % of IAL', '33⅓ % of IA2, 16⅔ % of IAL',
                    None, None,
                ),
                'duration': '1 hour 30 minutes',
                'grading': GS.AL.SINGLE_AE,
                'internal': False,
                'optional': True,
            },
            {
                'name': 'S1: Statistics 1',
                'code': 'WST01',
                'mark': 75,
                'mark_adjusted': 100,
                'mark_adjusted_type': MT.UMS,
                'grading': GS.AL.SINGLE_AE,
                'weighting': (
                    '33⅓ % of IAS, 16⅔ % of IAL', '33⅓ % of IA2, 16⅔ % of IAL',
                    '33⅓ % of IAS, 16⅔ % of IAL', '33⅓ % of IA2, 16⅔ % of IAL',
                    None, None,
                ),
                'duration': '1 hour 30 minutes',
                'internal': False,
                'optional': True
            },
            {
                'name': 'FP1: Further Pure Mathematics 1',
                'code': 'WFM01/01',
                'mark': 75,
                'mark_adjusted': 100,
                'weighting': (
                    None, None,
                    '33⅓ % of IAS, 16⅔ % of IAL', '33⅓ % of IA2, 16⅔ % of IAL',
                    '33⅓ % of IAS, 16⅔ % of IAL', '33⅓ % of IA2, 16⅔ % of IAL',
                ),
                'mark_adjusted_type': MT.UMS,
                'grading': GS.AL.SINGLE_ASE,
                'duration': '1 hour 30 minutes',
                'internal': False,
                'optional': False,
                'series': [Ser.Exam.JAN, Ser.Exam.JUN],
            },
            
            {
                'name': 'FP2: Further Pure Mathematics 2',
                'code': 'WFM02/01',
                'mark': 75,
                'mark_adjusted': 100,
                'weighting': (
                    None, None,
                    '33⅓ % of IAS, 16⅔ % of IAL', '33⅓ % of IA2, 16⅔ % of IAL',
                    None, '33⅓ % of IA2, 16⅔ % of IAL',
                ),
                'mark_adjusted_type': MT.UMS,
                'grading': GS.AL.SINGLE_ASE,
                'duration': '1 hour 30 minutes',
                'internal': False,
                'optional': True,
                'series': [Ser.Exam.JAN, Ser.Exam.JUN],
            },
            {
                'name': 'FP3: Further Pure Mathematics 3',
                'code': 'WFM03',
                'mark': 75,
                'mark_adjusted': 100,
                'weighting': (
                    None, None,
                    '33⅓ % of IAS, 16⅔ % of IAL', '33⅓ % of IA2, 16⅔ % of IAL',
                    None, '33⅓ % of IA2, 16⅔ % of IAL',
                ),
                'duration': '1 hour 30 minutes',
                'mark_adjusted_type': MT.UMS,
                'grading': GS.AL.SINGLE_ASE,
                'internal': False,
                'optional': True,
                'series': [Ser.Exam.JAN, Ser.Exam.JUN],
            },
            {
                'name': 'M2: Mechanics 2',
                'code': 'WME02/01',
                'mark': 75,
                'mark_adjusted': 100,
                'weighting': (
                    None, '33⅓ % of IA2, 16⅔ % of IAL',
                    '33⅓ % of IAS, 16⅔ % of IAL', '33⅓ % of IA2, 16⅔ % of IAL',
                    None, None,
                ),
                'duration': '1 hour 30 minutes',
                'mark_adjusted_type': MT.UMS,
                'grading': GS.AL.SINGLE_ASE,
                'internal': False,
            },
            {
                'name': 'M3: Mechanics 3',
                'code': 'WME03/01',
                'mark': 75,
                'mark_adjusted': 100,
                'weighting': (
                    None, None,
                    '33⅓ % of IAS, 16⅔ % of IAL', '33⅓ % of IA2, 16⅔ % of IAL',
                    None, None,
                ),
                'duration': '1 hour 30 minutes',
                'mark_adjusted_type': MT.UMS,
                'grading': GS.AL.SINGLE_ASE,
                'internal': False,
                'optional': True,
                'series': [Ser.Exam.JAN, Ser.Exam.JUN],
            },
            {
                'name': 'S2: Statistics 2',
                'code': 'WST02/01',
                'mark': 75,
                'mark_adjusted': 100,
                'weighting': (
                    None, '33⅓ % of IA2, 16⅔ % of IAL',
                    '33⅓ % of IAS, 16⅔ % of IAL', '33⅓ % of IA2, 16⅔ % of IAL',
                    None, None,
                ),
                'mark_adjusted_type': MT.UMS,
                'duration': '1 hour 30 minutes',
                'grading': GS.AL.SINGLE_ASE,
                'internal': False,
                'optional': True,
            },
            {
                'name': 'S3: Statistics 3',
                'code': 'WST03/01',
                'mark': 75,
                'mark_adjusted': 100,
                'mark_adjusted_type': MT.UMS,
                'weighting': (
                    None, None,
                    '33⅓ % of IAS, 16⅔ % of IAL', '33⅓ % of IA2, 16⅔ % of IAL',
                    None, None,
                ),
                'duration': '1 hour 30 minutes',
                'grading': GS.AL.SINGLE_ASE,
                'internal': False,
                'optional': True,
                'series': [Ser.Exam.JAN, Ser.Exam.JUN],
            }
        ]
    },
    {
        'subject': 'Physics',
        'code': 'XPH11',
        'group': SG.UK.SCIENCES,
        'name': QT.UKI.Edexcel.IAL.AS,
        'glh': 180,
        'first_assessment': 2019,
        'last_assessment': None,
        'current': True,
        'mark': 300,
        'mark_type': MT.UMS,
        'grading': GS.AL.SINGLE_AE, 
        'series': [Ser.Exam.JAN, Ser.Exam.JUN, Ser.Exam.OCT],
        'modular': True, 
        'sub_qualification': None,
        'components': [
            {
                'name': 'Unit 1: Mechanics and Materials',
                'code': 'WPH11/01',
                'mark': 80,
                'mark_adjusted': 120,
                'mark_adjusted_type': MT.UMS,
                'weighting': '40% of IAS, 20% of IAL',
                'duration': '1 hour 30 minutes',
                'grading': GS.AL.SINGLE_AE,
                'internal': False,
            },
            {
                'name': 'Unit 2: Waves and Electricity',
                'code': 'WPH12/01',
                'mark': 80,
                'mark_adjusted': 120,
                'mark_adjusted_type': MT.UMS,
                'weighting': '40% of IAS, 20% of IAL',
                'duration': '1 hour 30 miinutes',
                'grading': GS.AL.SINGLE_AE,
                'internal': False,
            },
            {
                'name': 'Unit 3: Practical Skills in Physics I',
                'code': 'WPH13/01',
                'mark': 50,
                'mark_adjusted': 60,
                'mark_adjusted_type': MT.UMS,
                'weighting': '20% of IAS, 10% of IAL', 
                'duration': '1 hour 20 minutes',
                'grading': GS.AL.SINGLE_AE,
                'internal': False,
            },
        ]
    },
    {
        'subject': 'Physics',
        'code': 'YPH11',
        'group': SG.UK.SCIENCES,
        'name': QT.UKI.Edexcel.IAL.A2,
        'glh': 360,
        'first_assessment': 2019,
        'last_assessment': None,
        'current': True,
        'mark': 600,
        'mark_type': MT.UMS,
        'grading': (GS.AL.SINGLE_AE, GS.AL.SINGLE_ASE), 
        'series': [Ser.Exam.JAN, Ser.Exam.JUN, Ser.Exam.OCT],
        'modular': True, 
        'sub_qualification': {
            'name': QT.UKI.Edexcel.IAL.AS,
            'code': 'XPH11',
            'first_assessment': 2019,
        },
        'components': [
            {
                'name': 'Unit 4: Further Mechanics, Fields and Particles',
                'code': 'WPH14/01',
                'mark': 90,
                'mark_adjusted': 120,
                'mark_adjusted_type': MT.UMS,
                'weighting':  '40% of IA2, 20% of IAL',
                'duration': '1 hour 45 minutes',
                'grading': GS.AL.SINGLE_ASE,
                'internal': False,
            },
            {
                'name': 'Unit 5: Thermodynamics, Radiation, Oscillations and Cosmology',
                'code': 'WPH15/01',
                'mark': 90,
                'mark_adjusted': 120,
                'mark_adjusted_type': MT.UMS,
                'weighting': '40% of IA2, 20% of IAL',
                'duration': '1 hour 45 minutes',
                'grading': GS.AL.SINGLE_ASE,
                'internal': False,
            },
            {
                'name': 'Unit 6: Practical Skills in Physics II',
                'code': 'WPH16/01',
                'mark': 50,
                'mark_adjusted': 60,
                'mark_adjusted_type': MT.UMS,
                'weighting': '20 % of IA2, 10% of IAL',
                'duration': '1 hour 20 minutes',
                'grading': GS.AL.SINGLE_ASE,
                'internal': False,
            }
        ]
    },
]







""" 


OLD = [
    {
        'subject': 'Chemistry',
        'code': ('XCH11', 'YCH11'),
        'kind': (QK.UKI.IAL.AS, QK.UKI.IAL.A2),
        'name': (QT.UKI.Edexcel.IAL.AS, QT.UKI.Edexcel.IAL.A2),
        'suite': QT.UKI.Edexcel.IAL._SUITE,
        'board': Board.EDEXCEL,
        'glh': (180, 360),
        'first_assessment': 2019,
        'mark': (300, 600),
        'glh': (180, 360),
        'mark_type': MT.UMS,
        'grading': (GS.AL.SINGLE_AE, GS.AL.SINGLE_ASE), 
        'series': [Ser.Exam.JAN, Ser.Exam.JUN, Ser.Exam.OCT],
        'modular': True,
        'components': [
            {
                'name': 'Unit 1: Structure, Bonding and Introduction to Organic Chemistry',
                'code': 'WCH11',
                'mark': 80,
                'mark_adjusted': 120,
                'weighting': (0, 0),
                'duration': '? hour',
                'grading': GS.AL.SINGLE_AE,
                'internal': False,
                'glh': 60,
            },
            {
                'name': 'Unit 2: Energetics, Group Chemistry, Haloenoalkanes and Alcohol',
                'code': 'WCH12',
                'mark': 80,
                'mark_adjusted': 120,
                'weighting': (0, 0),
                'duration': '? hour',
                'grading': GS.AL.SINGLE_AE,
                'internal': False,
            },
            {
                'name': 'Unit 3: Practical Skills in Chemistry I',
                'code': 'WCH13',
                'mark': 50,
                'mark_adjusted': 60,
                'weighting': (0, 0),
                'duration': '? hour',
                'grading': GS.AL.SINGLE_AE,
                'internal': False,
                'glh': 60,
            },
            {
                'name': 'Unit 4: Rates, Equilibria and Further Organic Chemistry',
                'code': 'WCH14',
                'mark': 80,
                'mark_adjusted': 120,
                'weighting': (None, 0),
                'duration': '? hour',
                'grading': GS.AL.SINGLE_ASE,
                'internal': False,
                'glh': 60,
            },
            {
                'name': 'Unit 5: Transition Metals and Organic Nitrogen Chemistry',
                'code': 'WCH15',
                'mark': 80,
                'mark_adjusted': 120,
                'weighting': (None, 0),
                'duration': '? hour',
                'grading': GS.AL.SINGLE_ASE,
                'internal': False,
                'glh': 60,
            },
            {
                'name': 'Unit 6: Practical Skills in Chemistry II',
                'code': 'WCH16',
                'mark': 50,
                'mark_adjusted': 60,
                'weighting': (None, 0),
                'duration': '? hour',
                'grading': GS.AL.SINGLE_ASE,
                'internal': False,
                'glh': 60,
            }
        ]
    },

    {
        'name': 'Business',
        'code': ('XBS11', 'YBS11'),
        'kind': (QK.UKI.IAL.AS, QK.UKI.IAL.A2),
        'name': (QT.UKI.Edexcel.IAL.AS, QT.UKI.Edexcel.IAL.A2),
        'suite': QT.UKI.Edexcel.IAL._SUITE,
        'board': Board.EDEXCEL,
        'group': SG.UK.PROFESSIONAL,
        'glh': (180, 360),
        'first_assessment': 2019,
        'mark': (200, 400),
        'glh': (180, 360),
        'mark_type': MT.UMS,
        'grading': (GS.AL.SINGLE_AE, GS.AL.SINGLE_ASE), 
        'series': [Ser.Exam.JAN, Ser.Exam.JUN, Ser.Exam.OCT],
        'modular': True,
        'components': [
            {
                'name': 'Unit 1: Marketing and People',
                'code': 'WBS11',
                'mark': 80,
                'mark_adjusted': 100,
                'weighting': (0, 0),
                'duration': '? hour',
                'grading': GS.AL.SINGLE_AE,
                'internal': False,
            },
            {
                'name': 'Unit 2: Managing Business Activities',
                'code': 'WBS12',
                'mark': 80,
                'mark_adjusted': 100,
                'weighting': (0, 0),
                'duration': '? hour',
                'grading': GS.AL.SINGLE_AE,
                'internal': False,
            },
            {
                'name': 'Unit 3: Business Decisions And Strategy',
                'code': 'WBS13',
                'mark': 80,
                'mark_adjusted': 100,
                'weighting': (None, 0),
                'duration': '? hour',
                'grading': GS.AL.SINGLE_ASE,
                'internal': False,

            },
            {
                'name': 'Unit 4: Global Business',
                'code': 'WBS14',
                'mark': 80,
                'mark_adjusted': 100,
                'weighting': (None, 0),
                'duration': '? hour',
                'grading': GS.AL.SINGLE_ASE,
                'internal': False,
            }
        ]
    },
    {
        'name': 'Economics',
        'code': ('XEC11', 'YEC11'),
        'kind': (QK.UKI.IAL.AS, QK.UKI.IAL.A2),
        'name': (QT.UKI.Edexcel.IAL.AS, QT.UKI.Edexcel.IAL.A2),
        'suite': QT.UKI.Edexcel.IAL._SUITE,
        'board': Board.EDEXCEL,
        'group': SG.UK.HUMANITIES,
        'glh': (180, 360),
        'first_assessment': 2019,
        'mark': (200, 400),
        'glh': (180, 360),
        'mark_type': MT.UMS,
        'grading': (GS.AL.SINGLE_AE, GS.AL.SINGLE_ASE), 
        'series': [Ser.Exam.JAN, Ser.Exam.JUN, Ser.Exam.OCT],
        'modular': True,
        'components': [
            {
                'name': 'Unit 1: Markets in Action',
                'code': 'WEC11',
                'mark': 80,
                'mark_adjusted': 100,
                'mark_adjusted_type': MT.UMS,
                'weighting': (0, 0),
                'duration': '? hour',
                'grading': GS.AL.SINGLE_AE,
                'internal': False,
            },
            {
                'name': 'Unit 2: Macroeconomic Performance and Policy',
                'code': 'WEC12',
                'mark': 80,
                'mark_adjusted': 100,
                'mark_adjusted_type': MT.UMS,
                'weighting': (0, 0),
                'duration': '? hour',
                'grading': GS.AL.SINGLE_AE,
                'internal': False,
            },
            {
                'name': 'Unit 3: Business Behaviour',
                'code': 'WEC13',
                'mark': 80,
                'mark_adjusted': 100,
                'mark_adjusted_type': MT.UMS,
                'weighting': (None, 0),
                'duration': '? hour',
                'grading': GS.AL.SINGLE_ASE,
                'internal': False,
            },
            {
                'name': 'Unit 4: Developments in the Global Economy',
                'code': 'WEC14',
                'mark': 80,
                'mark_adjusted': 100,
                'mark_adjusted_type': MT.UMS,
                'weighting': (None, 0),
                'duration': '? hour',
                'grading': GS.AL.SINGLE_ASE,
                'internal': False,
            }
        ]
    },
    {
        'name': 'English Language',
        'code': ('XEN01', 'YEN01'),
        'kind': (QK.UKI.IAL.AS, QK.UKI.IAL.A2),
        'name': (QT.UKI.Edexcel.IAL.AS, QT.UKI.Edexcel.IAL.A2),
        'suite': QT.UKI.Edexcel.IAL._SUITE,
        'board': Board.EDEXCEL,
        'group': SG.UK.ENGLISH,
        'first_assessment': 2016,
        'mark': (200, 400),
        'glh': (180, 360),
        'mark_type': MT.UMS,
        'grading': (GS.AL.SINGLE_AE, GS.AL.SINGLE_ASE), 
        'series': [Ser.Exam.JAN, Ser.Exam.JUN, Ser.Exam.OCT],
        'modular': True,
        'components': [
            {
                'name': 'Unit 1: Language: Context and Identity',
                'code': 'WEN01',
                'mark': 50,
                'mark_adjusted': 100,
                'weighting': (0, 0),
                'mark_adjusted_type': MT.UMS,
                'grading': GS.AL.SINGLE_AE,
                'duration': '? hour',
                'internal': False,
            },
            {
                'name': 'Unit 2: Language in Transition',
                'code': 'WEN02',
                'mark': 50,
                'mark_adjusted': 100,
                'mark_adjusted_type': MT.UMS,
                'grading': GS.AL.SINGLE_AE,
                'weighting': (0, 0),
                'duration': '? hour',
                'internal': False,
            },
            {
                'name': 'Unit 3: Crafting Language (Writing)',
                'code': 'WEN03',
                'mark': 50,
                'mark_adjusted': 100,
                'mark_adjusted_type': MT.UMS,
                'grading': GS.AL.SINGLE_ASE,
                'weighting': (None, 0),
                'duration': '? hour',
                'internal': False,
            },
            {
                'name': 'Unit 4: Investigating Language',
                'code': 'WEN04',
                'mark': 50,
                'mark_adjusted': 100,
                'mark_adjusted_type': MT.UMS,
                'grading': GS.AL.SINGLE_ASE,
                'weighting': (None, 0),
                'duration': '? hour',
                'internal': False,
            }
        ]
    },
   
    {
        'name': 'French',
        'code': ('XFR01', 'YFR01'),
        'kind': (QK.UKI.IAL.AS, QK.UKI.IAL.A2),
        'name': (QT.UKI.Edexcel.IAL.AS, QT.UKI.Edexcel.IAL.A2),
        'suite': QT.UKI.Edexcel.IAL._SUITE,
        'board': Board.EDEXCEL,
        'group': SG.UK.LANGUAGES,
        'first_assessment': 2017,
        'mark': (200, 400),
        'glh': (180, 360),
        'mark_type': MT.UMS,
        'grading': (GS.AL.SINGLE_AE, GS.AL.SINGLE_ASE), 
        'series': [Ser.Exam.JAN, Ser.Exam.JUN, Ser.Exam.OCT],
        'modular': True,
        'components': [
            {
                'name': 'Unit 1: Spoken Expression and Response',
                'code': 'WFR01',
                'mark': 40,
                'mark_adjusted': 60,
                'mark_adjusted_type': MT.UMS,
                'grading': GS.AL.SINGLE_AE,
                'weighting': (0, 0),
                'duration': '? hour',
                'internal': False,
            },
            {
                'name': 'Unit 2: Understanding and Written Response',
                'code': 'WFR02',
                'mark': 90,
                'mark_adjusted': 140,
                'mark_adjusted_type': MT.UMS,
                'grading': GS.AL.SINGLE_AE,
                'weighting': (0, 0),
                'duration': '? hour',
                'internal': False,
            },
            {
                'name': 'Unit 3: Understanding and Spoken Response',
                'code': 'WFR03',
                'mark': 40,
                'mark_adjusted': 60,
                'mark_adjusted_type': MT.UMS,
                'grading': GS.AL.SINGLE_ASE,
                'weighting': (0, 0),
                'duration': '? hour',
                'internal': False,
            },
            {
                'name': 'Unit 4: Research, Understanding and Written Response',
                'code': 'WFR04',
                'mark': 90,
                'mark_adjusted': 140,
                'mark_adjusted_type': MT.UMS,
                'grading': GS.AL.SINGLE_ASE,
                'weighting': (0, 0),
                'duration': '? hour',
                'internal': False,
            }
        ]
    },
    {
        'name': 'Geography',
        'code': ('XGE01', 'YGE01'),
        'kind': (QK.UKI.IAL.AS, QK.UKI.IAL.A2),
        'name': (QT.UKI.Edexcel.IAL.AS, QT.UKI.Edexcel.IAL.A2),
        'suite': QT.UKI.Edexcel.IAL._SUITE,
        'board': Board.EDEXCEL,
        'group': SG.UK.HUMANITIES,
        'first_assessment': 2017,
        'mark': (200, 400),
        'glh': (180, 360),
        'mark_type': MT.UMS,
        'grading': (GS.AL.SINGLE_AE, GS.AL.SINGLE_ASE), 
        'series': [Ser.Exam.JAN, Ser.Exam.JUN, Ser.Exam.OCT],
        'modular': True,
        'components': [
            {
                'name': 'Unit 1: Global Challenges',
                'code': 'WGE01',
                'mark': 90,
                'weighting': (0, 0),
                'mark_adjusted': 120,
                'mark_adjusted_type': MT.UMS,
                'grading': GS.AL.SINGLE_AE,
                'weighting': (0, 0),
                'duration': '? hour',
                'internal': False,
            },
            {
                'name': 'Unit 2: Geographical Investigations',
                'code': 'WGE02',
                'mark': 60,
                'mark_adjusted': 80,
                'weighting': (0, 0),
                'mark_adjusted_type': MT.UMS,
                'grading': GS.AL.SINGLE_AE,
                'weighting': (0, 0),
                'duration': '? hour',
                'internal': False,
            },
            {
                'name': 'Unit 3: Contested Planet',
                'code': 'WGE03',
                'weighting': (None, 0),
                'mark': 90,
                'mark_adjusted': 120,
                'mark_adjusted_type': MT.UMS,
                'grading': GS.AL.SINGLE_ASE,
                'weighting': (0, 0),
                'duration': '? hour',
                'internal': False,
            },
            {
                'name': 'Unit 4: Researching Geography',
                'code': 'WGE04',
                'weighting': (None, 0),
                'mark': 60,
                'mark_adjusted': 80,
                'mark_adjusted_type': MT.UMS,
                'grading': GS.AL.SINGLE_ASE,
                'weighting': (0, 0),
                'duration': '? hour',
                'internal': False,
            }
        ]
    },

    {
        'name': 'Physics',
        'code': ('XPH11', 'YPH11'),
        'kind': (QK.UKI.IAL.AS, QK.UKI.IAL.A2),
        'name': (QT.UKI.Edexcel.IAL.AS, QT.UKI.Edexcel.IAL.A2),
        'suite': QT.UKI.Edexcel.IAL._SUITE,
        'board': Board.EDEXCEL,
        'group': SG.UK.SCIENCES,
        'first_assessment': (2016, 2016),
        'mark': (300, 600),
        'mark_type': MT.UMS,
        'grading': (GS.AL.SINGLE_AE, GS.AL.SINGLE_ASE), 
        'series': [Ser.Exam.JAN, Ser.Exam.JUN, Ser.Exam.OCT],
        'modular': True,
        'components': [
            {
                'name': 'Unit 1: Mechanics and Materials',
                'code': 'WPH11',
                'mark': 80,
                'weighting': (0, 0),
                'mark_adjusted': 120,
                'mark_adjusted_type': MT.UMS,
                'grading': GS.AL.SINGLE_AE,
                'duration': '? hour',
                'internal': False,
            },
            {
                'name': 'Unit 2: Waves and Electricity',
                'code': 'WPH12',
                'mark': 80,
                'weighting': (0, 0),
                'mark_adjusted': 120,
                'mark_adjusted_type': MT.UMS,
                'grading': GS.AL.SINGLE_AE,
                'duration': '? hour',
                'internal': False,
            },
            {
                'name': 'Unit 3: Practical Skills in Physics I',
                'code': 'WPH13',
                'mark': 50,
                'weighting': (0, 0),
                'mark_adjusted': 60,
                'mark_adjusted_type': MT.UMS,
                'grading': GS.AL.SINGLE_AE,
                'weighting': (0, 0),
                'duration': '? hour',
                'internal': False,
            },
            {
                'name': 'Unit 4: Further Mechanics, Fields and Particles',
                'code': 'WPH14',
                'mark': 80,
                'mark_adjusted': 120,
                'mark_adjusted_type': MT.UMS,
                'grading': GS.AL.SINGLE_ASE,
                'weighting': (0, 0),
                'duration': '? hour',
                'internal': False,
            },
            {
                'name': 'Unit 5: Thermodynamics, Radiation, Oscillations and Cosmology',
                'code': 'WPH15',
                'mark': 80,
                'weighting': (0, 0),
                'mark_adjusted': 120,
                'mark_adjusted_type': MT.UMS,
                'grading': GS.AL.SINGLE_ASE,
                'weighting': (0, 0),
                'duration': '? hour',
                'internal': False,
            },
            {
                'name': 'Unit 6: Practical Skills in Physics II',
                'code': 'WPH16',
                'mark': 50,
                'weighting': (0, 0),
                'mark_adjusted': 60,
                'mark_adjusted_type': MT.UMS,
                'grading': GS.AL.SINGLE_ASE,
                'weighting': (0, 0),
                'duration': '? hour',
                'internal': False,
            }
        ]
    },
    {
        'name': 'Psychology',
        'code': ('XPS01', 'YPS01'),
        'kind': (QK.UKI.IAL.AS, QK.UKI.IAL.A2),
        'name': (QT.UKI.Edexcel.IAL.AS, QT.UKI.Edexcel.IAL.A2),
        'suite': QT.UKI.Edexcel.IAL._SUITE,
        'board': Board.EDEXCEL,
        'group': SG.UK.HUMANITIES,
        'first_assessment': 2016,
        'mark': (200, 400),
        'glh': (180, 360),
        'mark_type': MT.UMS,
        'grading': (GS.AL.SINGLE_AE, GS.AL.SINGLE_ASE), 
        'series': [Ser.Exam.JAN, Ser.Exam.JUN, Ser.Exam.OCT],
        'modular': True,
        'components': [
            {
                'name': 'Unit 1: Social and Cognitive Psychology',
                'code': 'WPS01',
                'mark': 64,
                'mark_adjusted': 80,
                'mark_adjusted_type': MT.UMS,
                'grading': GS.AL.SINGLE_AE,
                'weighting': (0, 0),
                'duration': '? hour',
                'internal': False,
            },
            {
                'name': 'Unit 2: Biological Psychology, Learning Theories and Development',
                'code': 'WPS02',
                'mark': 96,
                'mark_adjusted': 120,
                'mark_adjusted_type': MT.UMS,
                'grading': GS.AL.SINGLE_AE,
                'weighting': (0, 0),
                'duration': '? hour',
                'internal': False,
            },
            {
                'name': 'Unit 3: Applications of Psychology',
                'code': 'WPS03',
                'mark': 64,
                'mark_adjusted': 80,
                'mark_adjusted_type': MT.UMS,
                'grading': GS.AL.SINGLE_ASE,
                'weighting': (None, 0),
                'duration': '? hour',
                'internal': False,
            },
            {
                'name': 'Unit 4: Clinical Psychology and Psychological Skills',
                'code': 'WPS04',
                'mark': 96,
                'mark_adjusted': 120,
                'mark_adjusted_type': MT.UMS,
                'grading': GS.AL.SINGLE_ASE,
                'weighting': (None, 0),
                'duration': '? hour',
                'internal': False,
            }
        ]
    },
    {
        'name': 'Spanish',
        'code': ('XSP01', 'YSP01'),
        'kind': (QK.UKI.IAL.AS, QK.UKI.IAL.A2),
        'name': (QT.UKI.Edexcel.IAL.AS, QT.UKI.Edexcel.IAL.A2),
        'suite': QT.UKI.Edexcel.IAL._SUITE,
        'board': Board.EDEXCEL,
        'group': SG.UK.LANGUAGES,
        'first_assessment': 2017,
        'mark': (200, 400),
        'glh': (180, 360),
        'mark_type': MT.UMS,
        'grading': (GS.AL.SINGLE_AE, GS.AL.SINGLE_ASE), 
        'series': [Ser.Exam.JAN, Ser.Exam.JUN, Ser.Exam.OCT],
        'modular': True,
        'components': [
            {
                'name': 'Unit 1: Spoken Expression and Response',
                'code': 'WSP01',
                'mark': 40,
                'mark_adjusted': 60,
                'mark_adjusted_type': MT.UMS,
                'grading': GS.AL.SINGLE_AE,
                'weighting': (0, 0),
                'duration': '? hour',
                'internal': False,
            },
            {
                'name': 'Unit 2: Understanding and Written Response',
                'code': 'WSP02',
                'mark': 90,
                'mark_adjusted': 140,
                'mark_adjusted_type': MT.UMS,
                'grading': GS.AL.SINGLE_AE,
                'weighting': (0, 0),
                'duration': '? hour',
                'internal': False,
            },
            {
                'name': 'Unit 3: Understanding and Spoken Response',
                'code': 'WSP03',
                'mark': 40,
                'mark_adjusted': 60,
                'mark_adjusted_type': MT.UMS,
                'grading': GS.AL.SINGLE_ASE,
                'weighting': (None, 0),
                'duration': '? hour',
                'internal': False,
            },
            {
                'name': 'Unit 4: Research, Understanding and Written Response',
                'code': 'WSP04',
                'mark': 90,
                'mark_adjusted': 140,
                'mark_adjusted_type': MT.UMS,
                'grading': GS.AL.SINGLE_ASE,
                'weighting': (None, 0),
                'duration': '? hour',
                'internal': False,
            }
        ]
    }
]

 """