from subject_app.qualification_data import QK, QT, GS, Ser, SG, MT, Board, Tier


SUBJECTS = [
    {
        'name': 'English Language A',
        'code': '4EA1',
        'group': SG.UK.ENGLISH,
        'kind': QK.UKI.IGCSE.IGCSE,
        'name': QT.UKI.Edexcel.IGCSE.IGCSE,
        'suite': QT.UKI.Edexcel.IGCSE._SUITE,
        'board': Board.EDEXCEL,
        'first_assessment': 2018,
        'last_assessment': None,
        'current': True,
        'mark': 150,
        'mark_type': MT.SCALED,
        'grading': GS.GCSE_9.SINGLE_91,
        'series': [Ser.Exam.NOVEMBER, Ser.Exam.JUNE],
        'modular': False,
        'components': [
            {
                'name': 'Paper 1: Non-fiction Texts and Transactional Writing',
                'code': '*/01',
                'mark': 90,
                'weighting': 60,
                'duration': '2 hours 15 minutes',
                'grading': GS.GCSE_9.SINGLE_91,
                'internal': False,
                
            },
            {
                'name': 'Component 2: Poetry and Prose Texts and Imaginative Writing',
                'code': '*/02',
                'mark': 60,
                'weighting': 40,
                'duration': '1 hour 30 minutes',
                'grading': GS.GCSE_9.SINGLE_91,
                'internal': False,
            },
            {
                'name': 'Component 3: Poetry and Prose Texts and Imaginative Writing',
                'code': '*/03',
                'mark': 60,
                'weighting': 40,
                'duration': '',
                'grading': GS.GCSE_9.SINGLE_91,
                'internal': True,
            },
        ]
    },
    {
        'name': (
            'Mathematics A (Foundation Tier)',
            'Mathematics A (Higher Tier)',
        ),
        'code': '4MA1',
        'group': SG.UK.MATHS,
        'kind': QK.UKI.IGCSE.IGCSE,
        'name': QT.UKI.Edexcel.IGCSE.IGCSE,
        'suite': QT.UKI.Edexcel.IGCSE._SUITE,
        'first_assessment': 2018,
        'last_assessment': None,
        'current': True,
        'mark': 200,
        'mark_type': MT.SCALED,
        'tier': (Tier.CORE, Tier.EXTENDED),
        'grading': (GS.GCSE_9.SINGLE_51, GS.GCSE_9.SINGLE_93),
        'series': [Ser.Exam.JANUARY, Ser.Exam.JUNE],
        'modular': False,
        'components': [
            {
                'name': 'Paper 1F',
                'code': '*/1F',
                'mark': 100,
                'weighting': (50, None),
                'duration': '2 hours',
                'grading': GS.GCSE_9.SINGLE_51,
                'internal': False,
                
            },
            {
                'name': 'Paper 2F',
                'code': '*/2F',
                'mark': 100,
                'weighting': (50, None),
                'duration': '2 hours',
                'grading': GS.GCSE_9.SINGLE_51,
                'internal': False,
            },
            {
                'name': 'Paper 1H',
                'code': '*/1H',
                'mark': 100,
                'weighting': (None, 50),
                'duration': '2 hours',
                'grading': GS.GCSE_9.SINGLE_93,
                'internal': False,
            },
            {
                'name': 'Paper 2H',
                'code': '*/2H',
                'mark': 100,
                'weighting': (None, 50),
                'duration': '2 hours',
                'grading': GS.GCSE_9.SINGLE_93,
                'internal': False,
            }
        ]
    },
     {
        'name': (
            'Mathematics A (Modular) (Foundation Tier)',
            'Mathematics A (Modular) (Higher Tier)',
        ),
        'code': ('4XMAF', '4XMAH'),
        'group': SG.UK.MATHS,
        'kind': QK.UKI.IGCSE.IGCSE,
        'name': QT.UKI.Edexcel.IGCSE.IGCSE,
        'suite': QT.UKI.Edexcel.IGCSE._SUITE,
        'board': Board.EDEXCEL,
        'first_assessment': 2025,
        'last_assessment': None,
        'current': True,
        'mark': 200,
        'mark_type': MT.SCALED,
        'tier': (Tier.CORE, Tier.EXTENDED),
        'grading': (GS.GCSE_9.SINGLE_51, GS.GCSE_9.SINGLE_93),
        'series': [Ser.Exam.JANUARY, Ser.Exam.JUNE],
        'modular': True,
        'components': [
            {
                'name': 'Unit 1 Foundation Tier',
                'code': '4WM1F/01',
                'mark': 100,
                'weighting': (50, None),
                'duration': '2 hours',
                'grading': GS.GCSE_9.SINGLE_51,
                'internal': False,
            },
            {
                'name': 'Unit 2 Foundation Tier',
                'code': '4WM2F/01',
                'mark': 100,
                'weighting': (50, None),
                'duration': '2 hours',
                'grading': GS.GCSE_9.SINGLE_51,
                'internal': False,
            },
            {
                'name': 'Unit 1 Higher Tier',
                'code': '4WM1H/01',
                'mark': 100,
                'weighting': (None, 50),
                'duration': '2 hours',
                'grading': GS.GCSE_9.SINGLE_93,
                'internal': False,
            },
            {
                'name': 'Unit 2 Higher Tier',
                'code': '4WM2H/01',
                'mark': 100,
                'weighting': (None, 50),
                'duration': '2 hours',
                'grading': GS.GCSE_9.SINGLE_93,
                'internal': False,
            }
        ]
    },

    {
        'name': 'SCIENCE (Double Award)',
        'code': '4SD0',
        'group': SG.UK.SCIENCES,
        'kind': QK.UKI.IGCSE.IGCSE_DOUBLE,
        'name': QT.UKI.Edexcel.IGCSE.IGCSE,
        'suite': QT.UKI.Edexcel.IGCSE._SUITE,
        'first_assessment': 2019,
        'last_assessment': None,
        'current': True,
        'mark': 330,
        'mark_type': MT.SCALED,
        'grading': GS.GCSE_9.DOUBLE_91, 
        'series': [Ser.Exam.JUNE, Ser.Exam.NOVEMBER],
        'modular': False,
        'components': [
            {
                'name': 'Biology Paper 1',
                'code': '*/1B',
                'mark': 110,
                'weighting': 33.3,
                'duration': '2 hours',
                'grading': GS.GCSE_9.DOUBLE_91,
                'internal': False,
            },
            {
                'name': 'Chemistry Paper 1',
                'code': '*/1C',
                'mark': 110,
                'weighting': 33.3,
                'duration': '2 hours',
                'grading': GS.GCSE_9.DOUBLE_91,
                'internal': False,
            },
            {
                'name': 'Physics Paper 1',
                'code': '*/1P',
                'mark': 110,
                'weighting': 33.3,
                'duration': '2 hours',
                'grading': GS.GCSE_9.DOUBLE_91,
                'internal': False,
            },
        ]
    },
    {
        'name': 'SCIENCE (Double Award) (Modular)',
        'code': '4XSD1',
        'group': SG.UK.SCIENCES,
        'kind': QK.UKI.IGCSE.IGCSE_DOUBLE,
        'name': QT.UKI.Edexcel.IGCSE.IGCSE,
        'suite': QT.UKI.Edexcel.IGCSE._SUITE,
        'board': Board.EDEXCEL,
        'first_assessment': 2025,
        'last_assessment': None,
        'current': True,
        'mark': 330,
        'mark_type': MT.SCALED,
        'mark_ums': 480,
        'grading': GS.GCSE_9.DOUBLE_91, 
        'series': [Ser.Exam.JUNE, Ser.Exam.NOVEMBER],
        'modular': True,
        'components': [
            {
                'name': 'Biology Unit 1',
                'code': '4WSD1/1B',
                'mark': 60,
                'mark_adjusted': 80,
                'mark_adjusted_type': MT.UMS,
                'weighting': 16.6,
                'duration': '1 hour 10 minutes',
                'grading': GS.GCSE_9.SINGLE_91,
                'internal': False,
            },
            {
                'name': 'Biology Unit 2',
                'code': '4WSD2/1B',
                'mark': 60,
                'mark_adjusted': 80,
                'mark_adjusted_type': MT.UMS,
                'weighting': 16.6,
                'duration': '1 hour 10 minutes',
                'grading': GS.GCSE_9.SINGLE_91,
                'internal': False,
            },
           {
                'name': 'Chemistry Unit 3',
                'code': '4WSD3/1C',
                'mark': 60,
                'mark_adjusted': 80,
                'mark_adjusted_type': MT.UMS,
                'weighting': 16.6,
                'duration': '1 hour 10 minutes',
                'grading': GS.GCSE_9.SINGLE_91,
                'internal': False,
            },
            {
                'name': 'Chemistry Unit 4',
                'code': '4WSD4/1C',
                'mark': 60,
                'mark_adjusted': 80,
                'mark_adjusted_type': MT.UMS,
                'weighting': 16.6,
                'duration': '1 hour 10 minutes',
                'grading': GS.GCSE_9.SINGLE_91,
                'internal': False,
            },
            {
                'name': 'Physics Unit 5',
                'code': '4WSD6/1P',
                'mark': 60,
                'mark_adjusted': 80,
                'mark_adjusted_type': MT.UMS,
                'weighting': 16.6,
                'duration': '1 hour 10 minutes',
                'grading': GS.GCSE_9.SINGLE_91,
                'internal': False,
            },
            {
                'name': 'Physics Unit 6',
                'code': '4WSD6/1P',
                'mark': 60,
                'mark_adjusted': 80,
                'mark_adjusted_type': MT.UMS,
                'weighting': 16.6,
                'duration': '1 hour 10 minutes',
                'grading': GS.GCSE_9.SINGLE_91,
                'internal': False,
            },
        ]
    },
]