from choices import QT, GS, Ser, SG, MT
## QUALIFICATION COMPONENTS NEED TO BE FIXED INTO AS AND A2 COMPOMEMTS
QUALIFICATIONS = [
    {
        'subject': 'Biology',
        'name': (QT.UKI.CIE.IAL.AS, QT.UKI.CIE.IAL.A2),
        'code': '9700',
        'group': SG.UK.SCIENCES,
        'glh': (180, 360),
        'first_assessment': 2024,
        'mark': (130, 260),
        'mark_type': MT.SCALED,
        'mark_secondary': 100,
        'mark_secondary_type': MT.PUM,
        'grading': (GS.AL.SINGLE_AE, GS.AL.SINGLE_ASE), 
        'series': [Ser.Exam.MAR, Ser.Exam.JUN, Ser.Exam.NOV],
        'modular': False,
        'components': [
            {
                'name': 'Paper 1: Multiple Choice',
                'code': '*/1',
                'mark': 40,
                'weighting': ('31%', '15.5%'),
                'duration': '1 hour 15 minutes',
                'internal': False,
                'grading': GS.AL.SINGLE_AE,
                'optional': (False, True)
            },
            {
                'name': 'Paper 2: AS Level Structured Questions',
                'code': '*/2',
                'mark': 80,
                'weighting': ('46 % of AS, 22 % of AL', '22 %'),
                'duration': '1 hour 15 minutes',
                'internal': False,
                'grading': GS.AL.SINGLE_AE,
                'optional': (False, True)
            },
            {
                'name': 'Paper 3: Advanced Practical Skills',
                'code': '*/3',
                'mark': 40,
                'weighting': ('23 % of AS, 11.5 % of IAL', '11.5 % of IAL'),
                'duration': '2 hours',
                'internal': False,
                'grading': GS.AL.SINGLE_AE,
                'optional': (False, True)
            },
            {
                'name': 'Paper 4: A Level Structured Questions',
                'code': '*/4',
                'mark': 100,
                'weighting': (None, '77 % of A2, 38.5 % of AL'),
                'duration': '2 hours',
                'internal': False,
                'grading': GS.AL.SINGLE_AE,
                'optional': False
            },
            {
                'name': 'Paper 5: Planning, Analysis and Evaluation',
                'code': '*/5',
                'mark': 30,
                'weighting': (None, '23 % of A2, 11.5 % of AL'),
                'duration': '2 hours',
                'internal': False,
                'grading': GS.AL.SINGLE_AE,
                'optional': False
            },
        ]
    },
    {
        'subject': 'Business',
        'code': '9609',
        'name': (QT.UKI.CIE.IAL.AS, QT.UKI.CIE.IAL.A2),
        'group': SG.UK.PROFESSIONAL,
        'glh': (180, 360),
        'first_assessment': 2024,
        'mark': (100, 200),
        'mark_type': MT.SCALED,
        'mark_secondary': 100,
        'mark_secondary_type': MT.PUM,
        'grading': (GS.AL.SINGLE_AE, GS.AL.SINGLE_ASE), 
        'series': [Ser.Exam.MAR, Ser.Exam.JUN, Ser.Exam.NOV],
        'modular': False,
        'components': [
            {
                'name': 'Paper 1: Business Concepts 1',
                'code': '*/1',
                'mark': 40,
                'eligible': (True, True),
                'weighting': ('40%', '20%'),
                'duration': '1 hour 15 minutes',
                'internal': False,
                'grading': GS.AL.SINGLE_AE,    
            },
            {
                'name': 'Paper 2: Business Concepts 2',
                'code': '*/2',
                'mark': 60,
                'weighting': ('30%', '30%'),
                'duration': '1 hour 30 minutes',
                'internal': False,
                'grading': GS.AL.SINGLE_AE,
            },
            {
                'name': 'Paper 3: Business Decision-Making',
                'code': '*/3',
                'mark': 60,
                'weighting': (None, 30),
                'duration': '1 hour 45 minutes',
                'internal': False,
                'grading': GS.AL.SINGLE_AE,
            },
            {
                'name': 'Paper 4: Business Strategy',
                'code': '*/4',
                'mark': 40,
                'weighting': (None, '20%'),
                'duration': '1 hour 15 minutes',
                'internal': False,
                'grading': GS.AL.SINGLE_AE,
            }
        ]
    },
    {
        'subject': 'Mathematics',
        'code': '9709',
        'name': (QT.UKI.CIE.IAL.AS, QT.UKI.CIE.IAL.A2),
        'group': SG.UK.MATHS,
        'glh': (180, 360),
        'first_assessment': 2024,
        'mark': (125, 250),
        'mark_type': MT.SCALED,
        'mark_secondary': 100,
        'mark_secondary_type': MT.PUM,
        'grading': (GS.AL.SINGLE_AE, GS.AL.SINGLE_ASE), 
        'series': [Ser.Exam.MAR, Ser.Exam.JUN, Ser.Exam.NOV],
        'modular': False,
        'components': [
            {
                'name': 'Paper 1: Pure Mathematics 1',
                'code': '*/1',
                'mark': 75,
                'weighting': ('30%', '30%'),
                'duration': '1 hour 50 minutes',
                'internal': False,
                'grading': GS.AL.SINGLE_AE,
                'optional': False,
            },
            {
                'name': 'Paper 2: Pure Mathematics 2',
                'code': '*/2',
                'mark': 50,
                'weighting': (40, None),
                'duration': '1 hour 15 minutes',
                'internal': False,
                'grading': GS.AL.SINGLE_AE,
                'optional': True,
            },
            {
                'name': 'Paper 3: Pure Mathematics 3',
                'code': '*/3',
                'mark': 75,
                'weighting': (None, 30),
                'duration': '1 hour 50 minutes',
                'internal': False,
                'grading': GS.AL.SINGLE_AE,
                'optional': False,
            },
            {
                'name': 'Paper 4: Mechanics',
                'code': '9709/4',
                'mark': 50,
                'weighting': ('40%', '20%'),
                'duration': '1 hour 15 minutes',
                'internal': False,
                'grading': GS.AL.SINGLE_AE,
                'optional': True,
            },
            {
                'name': 'Paper 5: Probability & Statistics 1',
                'code': '*/5',
                'mark': 50,
                'weighting': ('40%', '20%'),
                'duration': '1 hour 15 minutes',
                'internal': False,
                'grading': GS.AL.SINGLE_AE,
                'optional': True,
            },
            {
                'name': 'Paper 6: Probability & Statistics 2',
                'code': '*/6',
                'mark': 50,
                'weighting': (None, '20%'),
                'duration': '1 hour 15 minutes',
                'internal': False,
                'grading': GS.AL.SINGLE_AE,
                'optional': True,
            }
        ]
    },
    {
        'subject': 'Media',
        'code': '9607',
        'group': SG.UK.PROFESSIONAL,
        'name': (QT.UKI.CIE.IAL.AS, QT.UKI.CIE.IAL.A2),
        'glh': (180, 360),
        'first_assessment': 2024,
        'mark': (100, 210),
        'mark_type': MT.SCALED,
        'grading': (GS.AL.SINGLE_AE, GS.AL.SINGLE_ASE), 
        'series': [Ser.Exam.MAR, Ser.Exam.JUN, Ser.Exam.NOV],
        'modular': False,
        'components': [
            {
                'name': 'Component 1: Foundation Portfolio',
                'code': '*/1',
                'mark': 50,
                'weighting': ('50%', '25%'),
                'duration': '',
                'internal': False,
                'grading': GS.AL.SINGLE_AE,
            },
            {
                'name': 'Component 2: Media texts and contexts',
                'code': '*/2',
                'mark': 50,
                'weighting': ('50%', '25%'),
                'duration': '2 hours',
                'internal': False,
                'grading': GS.AL.SINGLE_AE,
            },
            {
                'name': 'Component 3: Advanced Portfolio',
                'code': '*/3',
                'mark': 50,
                'weighting': (None, '25%'),
                'duration': '',
                'internal': False,
                'grading': GS.AL.SINGLE_AE,
            },
            {
                'name': 'Component 4: Critical Perspectives',
                'code': '*/4',
                'mark': 60,
                'weighting': (None, '25%'),
                'duration': '2 hours',
                'internal': False,
                'grading': GS.AL.SINGLE_AE,
            }
        ]
    }
]
