from choices import QT, GS, Ser, SG, MT

QUALIFICATIONS = [
        {
        'subject': 'Applied Business',
        'code': ('1831', '1832'),
        'group': SG.UK.PROFESSIONAL,
        'name': (QT.UKN.AQA.AG.CERT, QT.UKN.AQA.AG.EXT_CERT),
        'glh': (180, 360),
        'first_assessment': 2016,
        'last_assessment': None,
        'current': True,
        'mark': (300, 600),
        'mark_type': MT.UMS,
        'grading': GS.AGQ.SINGLE_DSP,
        'series': [Ser.Exam.JAN, Ser.Exam.MAYJUN],
        'modular': False, 
        'components': [
            {
                'name': 'Unit 1: Financial planning and analysis',
                'code': '*/ABS1',
                'mark': 60,
                'mark_type': MT.RAW,
                'adjusted_mark': 100,
                'adjusted_mark_type': MT.UMS,
                'duration': '1 hour',
                'weighting':  ('33⅓ %', '16⅔ %'),
                'glh': 60,
                'grading': GS.AGQ.SINGLE_DN,
                'internal': False,
                'optional': False,
            },
            {
                'name': 'Unit 2: Financial planning and analysis',
                'code': '*/ABS2',
                'mark': None,
                'mark_type': MT.NONE,
                'duration': '',
                'weighting':  ('33⅓ %', '16⅔ %'),
                'glh': 60,
                'grading': GS.AGQ.SINGLE_DP,
                'internal': True,
                'optional': False,
            },
            {
                'name': 'Unit 3: Entrepreneurial opportunities',
                'code': '*/ABS3',
                'mark': 60,
                'mark_type': MT.RAW,
                'adjusted_mark': 100,
                'adjusted_mark_type': MT.UMS,
                'duration': '1 hour',
                'weighting':  ('33⅓ %', '16⅔ %'),
                'glh': 60,
                'grading': GS.AGQ.SINGLE_DN,
                'internal': False,
                'optional': False,
            },
            {
                'name': 'Unit 4: Managing and leading people',
                'code': '*/ABS4',
                'mark': 60,
                'mark_type': MT.RAW,
                'adjusted_mark': 100,
                'adjusted_mark_type': MT.UMS,
                'duration': '1 hour',
                'weighting':  (None, '16⅔ %'),
                'glh': 60,
                'grading': GS.AGQ.SINGLE_DN,
                'internal': False,
                'optional': False,
            },
            {
                'name': 'Unit 5: Developing a business proposal',
                'code': '*/ABS5',
                'mark': None,
                'mark_type': MT.NONE,
                'duration': '',
                'weighting':  (None, '16⅔ %'),
                'glh': 60,
                'grading': GS.AGQ.SINGLE_DN,
                'internal': True,
                'optional': False,
            },
            {
                'name': 'Unit 6: e-Business implementation',
                'code': '*/ABS6',
                'mark': None,
                'mark_type': MT.NONE,
                'duration': '',
                'weighting':  (None, '16⅔ %'),
                'glh': 60,
                'grading': GS.AGQ.SINGLE_DN,
                'internal': True,
                'optional': True,
            },
            {
                'name': 'Unit 7: Managing an event',
                'code': '*/ABS7',
                'mark': None,
                'mark_type': MT.NONE,
                'duration': '',
                'weighting':  (None, '16⅔ %'),
                'glh': 60,
                'grading': GS.AGQ.SINGLE_DN,
                'internal': True,
                'optional': True,
            },
            {
                'name': 'Unit 8: Marketing communications',
                'code': '*/ABS8',
                'mark': None,
                'mark_type': MT.NONE,
                'duration': '',
                'weighting':  (None, '16⅔ %'),
                'glh': 60,
                'grading': GS.AGQ.SINGLE_DN,
                'internal': True,
                'optional': True,
            },
        ]
    },
]