from subject_app.models import Programme, Board
from register_app.edusystem import QualificationType as QT 
from register_app.edusystem import GradingScale as GS
from register_app.edusystem import ExamSeries as ES
from register_app.edusystem import SubjectGroup as SG
from register_app.edusystem import MarkType as MT

SUBJECTS = [
        {
        'name': 'CLASSICAL CIVILISATION',
        'code': 'H408',
        'group': SG.British.HUMANITIES,
        'qualification': QT.British.A2,
        'programme': Programme.British.ALEVEL,
        'board': Board.OCR,
        'first_assessment': 2019,
        'last_assessment': None,
        'mark': 250,
        'mark_type': MT.SCALED,
        'grading': GS.ALevel.SINGLE_ASE, 
        'series': [ES.JUNE],
        'modular': False,
        'components': [
            {
                'name': 'The World of the Hero',
                'code': 'H408/11',
                'mark': 100,
                'weighting': 40,
                'duration': '2 hours 30 minutes',
                'grading': GS.ALevel.SINGLE_ASE,
                'internal': False,
            },
            {
                'name': 'Greek Theatre',
                'code': 'H408/21',
                'mark': 75,
                'weighting': 30,
                'duration': '1 hour 45 minutes',
                'grading': GS.ALevel.SINGLE_ASE,
                'internal': False,
            },
            {
                'name': 'Imperial Image',
                'code': 'H408/22',
                'mark': 75,
                'weighting': 30,
                'duration': '1 hour 45 minutes',
                'grading': GS.ALevel.SINGLE_ASE,
                'internal': False,
            },
            {
                'name': 'Invention of the Barbarian',
                'code': 'H408/23',
                'mark': 75,
                'weighting': 30,
                'duration': '1 hour 45 minutes',
                'grading': GS.ALevel.SINGLE_ASE,
                'internal': False,
            },
            {
                'name': 'Greek Art',
                'code': 'H408/24',
                'mark': 75,
                'weighting': 30,
                'duration': '1 hour 45 minutes',
                'grading': GS.ALevel.SINGLE_ASE,
                'internal': False,
            },
            {
                'name': 'Greek Religion',
                'code': 'H408/31',
                'mark': 75,
                'weighting': 30,
                'duration': '1 hour 45 minutes',
                'grading': GS.ALevel.SINGLE_ASE,
                'internal': False,
            },
            {
                'name': 'Love and Relationships',
                'code': 'H408/32',
                'mark': 75,
                'weighting': 30,
                'duration': '1 hour 45 minutes',
                'grading': GS.ALevel.SINGLE_ASE,
                'internal': False,
            },
            {
                'name': 'Politics of the Late Republic',
                'code': 'H408/33',
                'mark': 75,
                'weighting': 30,
                'duration': '1 hour 45 minutes',
                'grading': GS.ALevel.SINGLE_ASE,
                'internal': False,
            },
            {
                'name': 'Democracy and the Athenians',
                'code': 'H408/34',
                'mark': 75,
                'weighting': 30,
                'duration': '1 hour 45 minutes',
                'grading': GS.ALevel.SINGLE_ASE,
                'internal': False,
            },
        ]
    },
    {
        'name': 'FURTHER MATHEMATICS B (MEI)',
        'code': 'H645',
        'group': SG.British.MATHS,
        'qualification': QT.British.A2,
        'programme': Programme.British.ALEVEL,
        'board': Board.OCR,
        'first_assessment': 2018,
        'mark': 360,
        'mark_type': MT.SCALED,
        'grading': GS.ALevel.SINGLE_ASE, 
        'series': [ES.JUNE],
        'modular': False,
        'components': [
            {
                'name': 'Core Pure',
                'code': 'Y420',
                'mark': 144,
                'weighting': 50,
                'duration': '2 hours 40 minutes',
                'grading': GS.ALevel.SINGLE_ASE,
                'internal': False,
            },
            {
                'name': ' Mechanics Major',
                'code': 'Y421',
                'mark': 120,
                'weighting': 33.3,
                'duration': '2 hours 15 minutes',
                'grading': GS.ALevel.SINGLE_ASE,
                'internal': False,
            },
            {
                'name': 'Statistics Major',
                'code': 'Y422',
                'mark': 120,
                'weighting': 33.3,
                'duration': '2 hours 15 minutes',
                'grading': GS.ALevel.SINGLE_ASE,
                'internal': False,
            },
            {
                'name': 'Mechanics Minor',
                'code': 'Y431',
                'mark': 60,
                'weighting': 16.7,
                'duration': '1 hour 15 minutes',
                'grading': GS.ALevel.SINGLE_ASE,
                'internal': False,
            },
            {
                'name': 'Statistics Minor',
                'code': 'Y432',
                'mark': 60,
                'weighting': 16.7,
                'duration': '1 hour 15 minutes',
                'grading': GS.ALevel.SINGLE_ASE,
                'internal': False,
            },
            {
                'name': 'Modelling with Algorithms',
                'code': 'Y433',
                'mark': 60,
                'weighting': 16.7,
                'duration': '1 hour 15 minutes',
                'grading': GS.ALevel.SINGLE_ASE,
                'internal': False,
            },
            {
                'name': 'Numerical Methods',
                'code': 'Y434',
                'mark': 60,
                'weighting': 33.3,
                'duration': '1 hour 15 minutes',
                'grading': GS.ALevel.SINGLE_ASE,
                'internal': False,
            },
            {
                'name': 'Extra Pure',
                'code': 'Y435',
                'mark': 60,
                'weighting': 16.7,
                'duration': '1 hour 15 minutes',
                'grading': GS.ALevel.SINGLE_ASE,
                'internal': False,
            },
            {
                'name': 'Further Pure with Technology',
                'code': 'Y436',
                'mark': 60,
                'weighting': 16.7,
                'duration': '1 hour 45 minutes',
                'grading': GS.ALevel.SINGLE_ASE,
                'internal': False,
            },
        ]
    },
]