from choices import QT, GS, Ser, SG, MT, Tier

QUALIFICATIONS = [
        {
        'subject': 'Chemistry A (Gateway Science)',
        'code': ('J248 F', 'J248 H'),
        'group': SG.UK.SCIENCES,
        'name': QT.UKN.OCR.GCSE.SINGLE,
        'glh': 120,
        'tier': (Tier.CORE, Tier.EXTENDED),
        'first_assessment': 2018,
        'mark': 180,
        'mark_type': MT.SCALED,
        'grading': (GS.GCSE_9.SINGLE_51, GS.GCSE_9.SINGLE_93), 
        'series': [Ser.Exam.JUN],
        'modular': False,
        'components': [
            {
                'name': 'Paper 1 (Foundation Tier)',
                'code': 'J248/01',
                'mark': 90,
                'weighting': ('50%', None),
                'duration': '1 hour 45 minutes',
                'grading': GS.GCSE_9.SINGLE_51,
                'internal': False,
            },
            {
                'name': 'Paper 2 (Foundation Tier)',
                'code': 'J248/02',
                'mark': 90,
                'weighting': ('50%', None),
                'duration': '1 hour 45 minutes',
                'grading': GS.GCSE_9.SINGLE_51,
                'internal': False,
            },
            {
                'name': 'Paper 3  (Higher Tier)',
                'code': 'J248/03',
                'mark': 90,
                'weighting': (None, '50%'),
                'duration': '1 hour 45 minutes',
                'grading': GS.GCSE_9.SINGLE_93,
                'internal': False,
            },
            {
                'name': 'Paper 4  (Higher Tier)',
                'code': 'J248/04',
                'mark': 90,
                'weighting': (None, '50%'),
                'duration': '1 hour 45 minutes',
                'grading': GS.GCSE_9.SINGLE_93,
                'internal': False,
            },
            
        ]
    },
    {
        'subject': 'Combined Science A (Gateway Science)',
        'code': ('J260 F', 'J260 H'),
        'group': SG.UK.SCIENCES,
        'name': QT.UKN.OCR.GCSE.DOUBLE,
        'glh': 240,
        'tier': (Tier.CORE, Tier.EXTENDED),
        'first_assessment': 2018,
        'mark': 360,
        'mark_type': MT.SCALED,
        'grading': (GS.GCSE_9.DOUBLE_51, GS.GCSE_9.DOUBLE_943), 
        'series': [Ser.Exam.JUN],
        'modular': False,
        'components': [
            {
                'name': 'Paper 1: Biology (Foundation Tier)',
                'code': 'J260/01',
                'mark': 60,
                'weighting': ('16⅔ %', None),
                'duration': '1 hour 10 minutes',
                'grading': GS.GCSE_9.DOUBLE_PAIRED_51,
                'internal': False,
            },
            {
                'name': 'Paper 2: Biology (Foundation Tier)',
                'code': 'J260/02',
                'mark': 60,
                'weighting': ('16⅔ %', None),
                'duration': '1 hour 10 minutes',
                'grading': GS.GCSE_9.DOUBLE_PAIRED_51,
                'internal': False,
            },
            {
                'name': 'Paper 3: Chemistry (Foundation Tier)',
                'code': 'J260/03',
                'mark': 60,
                'weighting': ('16⅔ %', None),
                'duration': '1 hour 10 minutes',
                'grading': GS.GCSE_9.DOUBLE_PAIRED_51,
                'internal': False,
            },
            {
                'name': 'Paper 4: Chemistry (Foundation Tier)',
                'code': 'J260/04',
                'mark': 60,
                'weighting': ('16⅔ %', None),
                'duration': '1 hour 10 minutes',
                'grading': GS.GCSE_9.DOUBLE_PAIRED_51,
                'internal': False,

            },
            {
                'name': 'Paper 5: Physics (Foundation Tier)',
                'code': 'J260/05',
                'mark': 60,
                'weighting': ('16⅔ %', None),
                'duration': '1 hour 10 minutes',
                'grading': GS.GCSE_9.DOUBLE_PAIRED_51,
                'internal': False,
            },
            {
                'name': 'Paper 6: Physics (Foundation Tier)',
                'code': 'J260/06',
                'mark': 60,
                'weighting': ('16⅔ %', None),
                'duration': '1 hour 10 minutes',
                'grading': GS.GCSE_9.DOUBLE_PAIRED_51,
                'internal': False,
            },
            {
                'name': 'Paper 7: Biology (Higher Tier)',
                'code': 'J260/07',
                'mark': 60,
                'weighting': (None, '16⅔ %'),
                'duration': '1 hour 10 minutes',
                'grading': GS.GCSE_9.DOUBLE_PAIRED_94,
                'internal': False,
            },
            {
                'name': 'Paper 8: Biology (Higher Tier)',
                'code': 'J260/08',
                'mark': 60,
                'weighting': (None, '16⅔ %'),
                'duration': '1 hour 10 minutes',
                'grading': GS.GCSE_9.DOUBLE_PAIRED_94,
                'internal': False,
            },
            {
                'name': 'Paper 9: Chemistry (Higher Tier)',
                'code': 'J260/09',
                'mark': 60,
                'weighting': (None, '16⅔ %'),
                'duration': '1 hour 10 minutes',
                'grading': GS.GCSE_9.DOUBLE_PAIRED_94,
                'internal': False,
            },
            {
                'name': 'Paper 10: Chemistry (Higher Tier)',
                'code': 'J260/10',
                'mark': 60,
                'weighting': (None, '16⅔ %'),
                'duration': '1 hour 10 minutes',
                'grading': GS.GCSE_9.SINGLE_51,
                'internal': False,
            },
            {
                'name': 'Paper 11: Physics (Higher Tier)',
                'code': 'J260/11',
                'mark': 60,
                'weighting': (None, '16⅔ %'),
                'duration': '1 hour 10 minutes',
                'grading': GS.GCSE_9.DOUBLE_PAIRED_94,
                'internal': False,
            },
            {
                'name': 'Paper 12: Physics (Foundation Tier)',
                'code': 'J260/12',
                'mark': 60,
                'weighting': (None, '16⅔ %'),
                'duration': '1 hour 10 minutes',
                'grading': GS.GCSE_9.DOUBLE_PAIRED_94,
                'internal': False,
            },
            
        ]
    },
]