# Generated by Django 5.1.5 on 2025-02-13 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "subject_app",
            "0003_alter_component_grading_alter_qualification_grading_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="qualification",
            name="mark_required",
            field=models.BooleanField(default=False),
        ),
    ]
