# Generated by Django 5.1.5 on 2025-02-14 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subject_app", "0005_alter_component_grading_alter_qualification_grading"),
    ]

    operations = [
        migrations.AddField(
            model_name="qualification",
            name="aggregate",
            field=models.BooleanField(default=False),
        ),
    ]
