# Generated by Django 5.1.5 on 2025-02-14 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("subject_app", "0006_qualification_aggregate"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="qualification",
            name="core",
        ),
    ]
