# Generated by Django 4.2.13 on 2025-01-25 10:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CheckpointEntry",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("grade", models.CharField(blank=True, max_length=20, null=True)),
                ("category", models.CharField(blank=True, max_length=40, null=True)),
                ("mark", models.FloatField(blank=True, null=True)),
                (
                    "comment",
                    models.TextField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MaxLengthValidator(2000)],
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ComponentExamResult",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "year",
                    models.SmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(2000),
                            django.core.validators.MaxValueValidator(2099),
                        ]
                    ),
                ),
                (
                    "series",
                    models.CharField(
                        choices=[
                            ("m.01", "January"),
                            ("m.02", "February"),
                            ("m.03", "March"),
                            ("m.04", "April"),
                            ("m.05", "May"),
                            ("m.05/06", "May/June"),
                            ("m.06", "June"),
                            ("m.09", "September"),
                            ("m.10", "October"),
                            ("m.11", "November"),
                            ("m.12", "December"),
                        ],
                        default="nan.undefined",
                        max_length=10,
                    ),
                ),
                ("grade", models.CharField(max_length=20)),
                (
                    "mark",
                    models.SmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1200),
                        ],
                    ),
                ),
                (
                    "mark_adjusted",
                    models.SmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1200),
                        ],
                    ),
                ),
                ("is_final", models.BooleanField(default=True)),
                ("available", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["-year", "-series"],
            },
        ),
        migrations.CreateModel(
            name="QualificationExamResult",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "year",
                    models.SmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(2000),
                            django.core.validators.MaxValueValidator(2099),
                        ]
                    ),
                ),
                (
                    "series",
                    models.CharField(
                        choices=[
                            ("m.01", "January"),
                            ("m.02", "February"),
                            ("m.03", "March"),
                            ("m.04", "April"),
                            ("m.05", "May"),
                            ("m.05/06", "May/June"),
                            ("m.06", "June"),
                            ("m.09", "September"),
                            ("m.10", "October"),
                            ("m.11", "November"),
                            ("m.12", "December"),
                        ],
                        default="nan.undefined",
                        max_length=10,
                    ),
                ),
                ("grade", models.CharField(max_length=20)),
                (
                    "mark",
                    models.SmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1200),
                        ],
                    ),
                ),
                (
                    "mark_secondary",
                    models.SmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1200),
                        ],
                    ),
                ),
                ("is_final", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["-year", "-series"],
            },
        ),
    ]
