# Generated by Django 4.2.13 on 2025-01-25 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("register_app", "0001_initial"),
        ("gradebook_app", "0001_initial"),
        ("subject_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="qualificationexamresult",
            name="student_qualification",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exam_entries",
                to="register_app.studentqualification",
            ),
        ),
        migrations.AddField(
            model_name="componentexamresult",
            name="component",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="entries",
                to="subject_app.component",
            ),
        ),
        migrations.AddField(
            model_name="componentexamresult",
            name="qualification_entry",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="components",
                to="gradebook_app.qualificationexamresult",
            ),
        ),
        migrations.AddField(
            model_name="componentexamresult",
            name="student_qualification",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exam_component_entries",
                to="register_app.studentqualification",
            ),
        ),
        migrations.AddField(
            model_name="checkpointentry",
            name="component",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mock_entries",
                to="subject_app.component",
            ),
        ),
        migrations.AddField(
            model_name="checkpointentry",
            name="enrollment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="checkpoint_entries",
                to="register_app.enrollment",
            ),
        ),
        migrations.AddField(
            model_name="checkpointentry",
            name="field",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="checkpoint_entries",
                to="register_app.checkpointfield",
            ),
        ),
        migrations.AddField(
            model_name="checkpointentry",
            name="student_qualification",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="checkpoint_entries",
                to="register_app.studentqualification",
            ),
        ),
        migrations.AddConstraint(
            model_name="qualificationexamresult",
            constraint=models.UniqueConstraint(
                fields=("year", "series", "student_qualification"),
                name="unique_qualification_exam_result",
            ),
        ),
        migrations.AddConstraint(
            model_name="componentexamresult",
            constraint=models.UniqueConstraint(
                fields=("year", "series", "student_qualification", "component"),
                name="unique_component_exam_result",
            ),
        ),
    ]
