# Generated by Django 4.2.13 on 2025-01-25 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("register_app", "0002_initial"),
        ("gradebook_app", "0003_checkpointentry_class_enrollment"),
    ]

    operations = [
        migrations.AddField(
            model_name="checkpointentry",
            name="enrollment_qualification",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="checkpoint_entries",
                to="register_app.enrollmentqualification",
            ),
        ),
    ]
