# Generated by Django 4.2.13 on 2025-01-25 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gradebook_app", "0004_checkpointentry_enrollment_qualification"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="checkpointentry",
            name="student_qualification",
        ),
    ]
