# Generated by Django 4.2.13 on 2025-01-25 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gradebook_app", "0005_remove_checkpointentry_student_qualification"),
    ]

    operations = [
        migrations.RenameField(
            model_name="checkpointentry",
            old_name="field",
            new_name="checkpoint_field",
        ),
    ]
