# Generated by Django 4.2.13 on 2025-01-27 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("register_app", "0004_checkpointyeargroup_enrollments_and_more"),
        ("gradebook_app", "0006_rename_field_checkpointentry_checkpoint_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="checkpointentry",
            name="checkpoint_yeargroup",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="checkpoint_entries",
                to="register_app.checkpointyeargroup",
            ),
            preserve_default=False,
        ),
    ]
