# Generated by Django 5.1.5 on 2025-02-12 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gradebook_app", "0007_checkpointentry_checkpoint_yeargroup"),
    ]

    operations = [
        migrations.AddField(
            model_name="checkpointentry",
            name="is_excluded",
            field=models.BooleanField(default=False),
        ),
    ]
