# Generated by Django 5.1.5 on 2025-02-13 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gradebook_app", "0008_checkpointentry_is_excluded"),
    ]

    operations = [
        migrations.AddField(
            model_name="checkpointentry",
            name="is_completed",
            field=models.BooleanField(default=False),
        ),
    ]
