# Generated by Django 5.1.5 on 2025-02-15 12:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gradebook_app", "0009_checkpointentry_is_completed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="checkpointentry",
            name="comment",
            field=models.TextField(
                blank=True,
                null=True,
                validators=[django.core.validators.MaxLengthValidator(2500)],
            ),
        ),
    ]
