# Generated by Django 5.1.5 on 2025-02-21 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gradebook_app", "0010_alter_checkpointentry_comment"),
        ("subject_app", "0008_alter_component_grading_alter_qualification_grading"),
    ]

    operations = [
        migrations.AlterField(
            model_name="checkpointentry",
            name="component",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mock_entries",
                to="subject_app.component",
                verbose_name="Exam component",
            ),
        ),
    ]
