# Generated by Django 5.1.5 on 2025-02-22 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gradebook_app", "0011_alter_checkpointentry_component"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="qualificationexamresult",
            options={"ordering": ["-is_final", "-year", "-series"]},
        ),
    ]
