# Generated by Django 5.1.5 on 2025-02-23 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gradebook_app", "0013_alter_componentexamresult_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="componentexamresult",
            options={"ordering": ["-is_final", "-year", "-series"]},
        ),
    ]
