from choices import QT, GS, Ser, SG, MT

QUALIFICATIONS = [
        {
        'subject': 'Applied Science',
        'code': '610/3965/2',
        'group': SG.UK.SCIENCES,
        'name': QT.UKN.BTEC.AAQ.EXT_CERT,
        'glh': 360,
        'first_assessment': 2026,
        'last_assessment': None,
        'current': True,
        'mark': (45, 45, 60, 120),
        'mark_type': MT.POINTS,
        'grading': GS.AGQ.SINGLE_DSP,
        'series': [Ser.Exam.JAN, Ser.Exam.MAYJUN],
        'modular': False, 
        'components': [
            {
                'name': 'Unit 1: Principles and Applications of Biology',
                'code': '*/01',
                'mark': 50,
                'mark_type': MT.RAW,
                'glh': 60,
                'weighting': 'glh',
                'duration': '1 hour',
                'grading': GS.AGQ.SINGLE_DN,
                'internal': False,
                'optional': False,
            },
            {
                'name': 'Unit 2: Principles and Applications of Chemistry',
                'code': '*/02',
                'mark': 50,
                'mark_type': MT.RAW,
                'glh': 60,
                'weighting': 'glh',
                'duration': '1 hour',
                'grading': GS.AGQ.SINGLE_DN,
                'internal': False,
                'optional': False,
            },
            {
                'name': 'Unit 4: Principles and Applications of Physics',
                'code': '*/03',
                'mark': None,
                'mark_type': MT.RAW,
                'glh': 60,
                'duration': '1 hour',
                'weighting': 'glh',
                'grading': GS.AGQ.SINGLE_DN,
                'internal': False,
                'optional': False,
            },
            {
                'name': 'Unit 4: Practical Scientific Procedures and Techniques ',
                'code': '*/04',
                'mark': None,
                'mark_type': MT.RAW,
                'glh': 60,
                'duration': '1 hour',
                'weighting': 'glh',
                'grading': GS.AGQ.SINGLE_DN,
                'internal': False,
                'optional': False,
            },
            {
                'name': 'Unit 5: Science Investigation Skills',
                'code': '*/05',
                'mark': None,
                'mark_type': MT.RAW,
                'glh': 90,
                'weighting': 'glh',
                'grading': GS.AGQ.SINGLE_DP,
                'internal': True,
                'optional': True,
            },
            {
                'name': 'Unit 6: Contemporary issues in Science',
                'code': '*/05',
                'mark': None,
                'mark_type': MT.RAW,
                'glh': 90,
                'weighting': 'glh',
                'grading': GS.AGQ.SINGLE_DP,
                'internal': True,
                'optional': True,
            },
        ]
    },
]