from choices import QT, GS, Ser, SG, MT

QUALIFICATIONS = [
        {
        'subject': (
            'Applied Science',
            'Application of Science',
            'Applied Science',
            'Applied Science',
        ),
        'code': ('610/3965/2', '600/4796/3', '600/6318/X', '601/4531/6'),
        'group': SG.UK.SCIENCES,
        'name': (
            QT.UKN.BTEC.FIRST.AWARD,
            QT.UKN.BTEC.FIRST.AWARD,
            QT.UKN.BTEC.FIRST.EXT_CERT,
            QT.UKN.BTEC.FIRST.DIP
        ),
        'glh': (120, 120, 360, 480),
        'first_assessment': 2014,
        'last_assessment': None,
        'current': True,
        'mark': (96, 96, 288, 384),
        'mark_type': MT.POINTS,
        'grading': GS.VTQ2.SINGLE_2DS1,
        'series': [Ser.Exam.FEB, Ser.Exam.JUN],
        'modular': False, 
        'components': [
            {
                'name': 'Unit 1: Principles of Science',
                'code': '20460E',
                'mark': 54,
                'mark_type': MT.RAW,
                'glh': 30,
                'weighting': ('glh', None, 'glh', 'glh'),
                'duration': '1 hour 15 minutes',
                'grading': GS.VTQ2.SINGLE_2D1,
                'internal': False,
                'optional': False,
            },
            {
                'name': 'Unit 2: Chemistry and our Earth',
                'code': '*/02',
                'mark': None,
                'mark_type': MT.NONE,
                'glh': 30,
                'weighting': ('glh', None, 'glh', 'glh'),
                'duration': '',
                'grading': GS.VTQ2.SINGLE_2D1,
                'internal': True,
                'optional': False,
            },
            {
            'name': 'Unit 3: Energy and our Universe',
            'code': '*/03',
            'mark': None,
            'mark_type': MT.NONE,
            'glh': 30,
            'weighting': ('glh', None, 'glh', 'glh'),
            'duration': '',
            'grading': GS.VTQ2.SINGLE_2D1,
            'internal': True,
            'optional': False,
        },
        {
            'name': 'Unit 4: Biology and our Environment',
            'code': '*/04',
            'mark': None,
            'mark_type': MT.NONE,
            'glh': 30,
            'weighting': ('glh', None, 'glh', 'glh'),
            'duration': '',
            'grading': GS.VTQ2.SINGLE_2D1,
            'internal': True,
            'optional': False,
        },
        {
            'name': 'Unit 5: Applications of Chemical Substances',
            'code': '*/05',
            'mark': None,
            'mark_type': MT.NONE,
            'glh': 30,
            'weighting': (None, 'glh', 'glh', 'glh'),
            'duration': '',
            'grading': GS.VTQ2.SINGLE_2D1,
            'internal': True,
            'optional': False,
        },
        {
            'name': 'Unit 6: Applications of Physical Science',
            'code': '*/06',
            'mark': None,
            'mark_type': MT.NONE,
            'glh': 30,
            'weighting': (None, 'glh', 'glh', 'glh'),
            'duration': '',
            'grading': GS.VTQ2.SINGLE_2D1,
            'internal': True,
            'optional': False,
        },
        {
            'name': 'Unit 7: Health Applications of Life Science',
            'code': '*/07',
            'mark': None,
            'mark_type': MT.NONE,
            'glh': 30,
            'weighting': (None, 'glh', 'glh', 'glh'),
            'duration': '',
            'grading': GS.VTQ2.SINGLE_2D1,
            'internal': True,
            'optional': False,
        },
        {
            'name': 'Unit 8: Scientific Skills',
            'code': '20474E',
            'mark': None,
            'mark_type': MT.NONE,
            'glh': 30,
            'weighting': (None, 'glh', 'glh', 'glh'),
            'duration': '1 hour 15  minutes',
            'grading': GS.VTQ2.SINGLE_2D1,
            'internal': False,
            'optional': False,
        },
        {
            'name': 'Unit 9: Practical Scientific Project',
            'code': '*/09',
            'mark': None,
            'mark_type': MT.NONE,
            'glh': 30,
            'weighting': (None, None, 'glh', 'glh'),
            'duration': '',
            'grading': GS.VTQ2.SINGLE_2D1,
            'internal': True,
            'optional': True,
        },
        {
            'name': 'Unit 10: World Energy',
            'code': '*/10',
            'mark': None,
            'mark_type': MT.NONE,
            'glh': 30,
            'weighting': (None, None, 'glh', 'glh'),
            'duration': '',
            'grading': GS.VTQ2.SINGLE_2D1,
            'internal': True,
            'optional': True,
        },
        {
            'name': 'Unit 11: How Scientific Theories are Formulated',
            'code': '*/11',
            'mark': None,
            'mark_type': MT.NONE,
            'glh': 30,
            'weighting': (None, None, 'glh', 'glh'),
            'duration': '',
            'grading': GS.VTQ2.SINGLE_2D1,
            'internal': True,
            'optional': True,
        },
        {
            'name': 'Unit 12: The Living Body',
            'code': '*/12',
            'mark': None,
            'mark_type': MT.NONE,
            'glh': 30,
            'weighting': (None, None, 'glh', 'glh'),
            'duration': '',
            'grading': GS.VTQ2.SINGLE_2D1,
            'internal': True,
            'optional': True,
        },
        {
            'name': 'Unit 13: Monitoring the Environment',
            'code': '*/13',
            'mark': None,
            'mark_type': MT.NONE,
            'glh': 30,
            'weighting': (None, None, 'glh', 'glh'),
            'duration': '',
            'grading': GS.VTQ2.SINGLE_2D1,
            'internal': True,
            'optional': True,
        },
        {
            'name': 'Unit 14: Growing Plants for Food',
            'code': '*/14',
            'mark': None,
            'mark_type': MT.NONE,
            'glh': 30,
            'weighting': (None, None, 'glh', 'glh'),
            'duration': '',
            'grading': GS.VTQ2.SINGLE_2D1,
            'internal': True,
            'optional': True,
        },
        {
            'name': 'Unit 15: Investigating a Crime Scene',
            'code': '*/15',
            'mark': None,
            'mark_type': MT.NONE,
            'glh': 30,
            'weighting': (None, None, 'glh', 'glh'),
            'duration': '',
            'grading': GS.VTQ2.SINGLE_2D1,
            'internal': True,
            'optional': True,
        },
        {
            'name': 'Unit 16: Science in Medicine',
            'code': '*/16',
            'mark': None,
            'mark_type': MT.NONE,
            'glh': 30,
            'weighting': (None, None, 'glh', 'glh'),
            'duration': '',
            'grading': GS.VTQ2.SINGLE_2D1,
            'internal': True,
            'optional': True,
        },
        {
            'name': 'Unit 17: Understanding Human Behaviour',
            'code': '*/17',
            'mark': None,
            'mark_type': MT.NONE,
            'glh': 30,
            'weighting': (None, None, 'glh', 'glh'),
            'duration': '',
            'grading': GS.VTQ2.SINGLE_2D1,
            'internal': True,
            'optional': True,
        },
        {
            'name': 'Unit 18: Designing and Making Useful Devices in Science',
            'code': '*/18',
            'mark': None,
            'mark_type': MT.NONE,
            'glh': 30,
            'weighting': (None, None, 'glh', 'glh'),
            'duration': '',
            'grading': GS.VTQ2.SINGLE_2D1,
            'internal': True,
            'optional': True,
        },
        {
            'name': 'Unit 19: Chemical Analysis and Detection',
            'code': '*/19',
            'mark': None,
            'mark_type': MT.NONE,
            'glh': 30,
            'weighting': (None, None, 'glh', 'glh'),
            'duration': '',
            'grading': GS.VTQ2.SINGLE_2D1,
            'internal': True,
            'optional': True,
        },
        {
            'name': 'Unit 20: Exploring our Universe',
            'code': '*/20',
            'mark': None,
            'mark_type': MT.NONE,
            'glh': 30,
            'weighting': (None, None, 'glh', 'glh'),
            'duration': '',
            'grading': GS.VTQ2.SINGLE_2D1,
            'internal': True,
            'optional': True,
        },
        {
            'name': 'Unit 21: Electronics in Action',
            'code': '*/21',
            'mark': None,
            'mark_type': MT.NONE,
            'glh': 30,
            'weighting': (None, None, 'glh', 'glh'),
            'duration': '',
            'grading': GS.VTQ2.SINGLE_2D1,
            'internal': True,
            'optional': True,
        },
        {
            'name': 'Unit 22: Biotechnology Procedures and Applications',
            'code': '*/22',
            'mark': None,
            'mark_type': MT.NONE,
            'glh': 30,
            'weighting': (None, None, 'glh', 'glh'),
            'duration': '',
            'grading': GS.VTQ2.SINGLE_2D1,
            'internal': True,
            'optional': True,
        },
        {
            'name': 'Unit 23: Further Chemistry',
            'code': '*/23',
            'mark': None,
            'mark_type': MT.NONE,
            'glh': 30,
            'weighting': (None, None, 'glh', 'glh'),
            'duration': '',
            'grading': GS.VTQ2.SINGLE_2D1,
            'internal': True,
            'optional': True,
        },
        {
            'name': 'Unit 24: Further Physics',
            'code': '*/24',
            'mark': None,
            'mark_type': MT.NONE,
            'glh': 30,
            'weighting': (None, None, 'glh', 'glh'),
            'duration': '',
            'grading': GS.VTQ2.SINGLE_2D1,
            'internal': True,
            'optional': True,
        }


        ]
    },
]