# Generated by Django 4.2.13 on 2025-01-25 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("register_app", "0001_initial"),
        ("subject_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="teachingclass",
            name="qualification",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teaching_classes",
                to="subject_app.qualification",
            ),
        ),
        migrations.AddField(
            model_name="teachingclass",
            name="teachers",
            field=models.ManyToManyField(
                related_name="teaching_classes", to="register_app.teacher"
            ),
        ),
        migrations.AddField(
            model_name="teachingclass",
            name="yeargroup",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teaching_classes",
                to="register_app.yeargroup",
                verbose_name="Year group (class)",
            ),
        ),
        migrations.AddField(
            model_name="teachertag",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teacher_tags",
                to="register_app.school",
            ),
        ),
        migrations.AddField(
            model_name="teacher",
            name="periods",
            field=models.ManyToManyField(
                blank=True,
                related_name="teachers",
                to="register_app.period",
                verbose_name="Academic periods",
            ),
        ),
        migrations.AddField(
            model_name="teacher",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teachers",
                to="register_app.school",
            ),
        ),
        migrations.AddField(
            model_name="teacher",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                related_name="teachers",
                to="register_app.teachertag",
                verbose_name="Tags",
            ),
        ),
        migrations.AddField(
            model_name="studenttag",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_tags",
                to="register_app.school",
            ),
        ),
        migrations.AddField(
            model_name="studentqualification",
            name="enrollments",
            field=models.ManyToManyField(
                blank=True,
                related_name="student_qualifications",
                through="register_app.EnrollmentQualification",
                to="register_app.enrollment",
                verbose_name="Enrollment periods",
            ),
        ),
        migrations.AddField(
            model_name="studentqualification",
            name="programme",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="qualifications",
                to="register_app.studentprogramme",
            ),
        ),
        migrations.AddField(
            model_name="studentqualification",
            name="qualification",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_qualifications",
                to="subject_app.qualification",
                verbose_name="Qualification title",
            ),
        ),
        migrations.AddField(
            model_name="studentqualification",
            name="sub_qualification",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="super_qualification",
                to="register_app.studentqualification",
            ),
        ),
        migrations.AddField(
            model_name="studentprogramme",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="programmes",
                to="register_app.student",
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="periods",
            field=models.ManyToManyField(
                blank=True,
                related_name="students",
                through="register_app.Enrollment",
                to="register_app.period",
                verbose_name="Academic periods",
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="students",
                to="register_app.school",
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                related_name="students",
                to="register_app.studenttag",
                verbose_name="Permanent student tags",
            ),
        ),
        migrations.AddField(
            model_name="period",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="periods",
                to="register_app.school",
            ),
        ),
        migrations.AddField(
            model_name="enrollmentqualification",
            name="enrollment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="enrollment_qualifications",
                to="register_app.enrollment",
                verbose_name="Enrollment",
            ),
        ),
        migrations.AddField(
            model_name="enrollmentqualification",
            name="student_qualification",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="enrollment_qualifications",
                to="register_app.studentqualification",
                verbose_name="Student qualification",
            ),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="period",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="enrollments",
                to="register_app.period",
            ),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="enrollments",
                to="register_app.student",
            ),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                related_name="enrollments",
                to="register_app.studenttag",
                verbose_name="Student enrollment tags",
            ),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="yeargroup",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="enrollments",
                to="register_app.yeargroup",
            ),
        ),
        migrations.AddField(
            model_name="classenrollment",
            name="enrollment_qualification",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="class_enrollments",
                to="register_app.enrollmentqualification",
                verbose_name="Enrollment qualification",
            ),
        ),
        migrations.AddField(
            model_name="classenrollment",
            name="teaching_class",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="class_enrollments",
                to="register_app.teachingclass",
                verbose_name="Teaching class",
            ),
        ),
        migrations.AddField(
            model_name="checkpointyeargroup",
            name="checkpoint",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="checkpoint_yeargroups",
                to="register_app.checkpoint",
            ),
        ),
        migrations.AddField(
            model_name="checkpointyeargroup",
            name="yeargroup",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="checkpoint_yeargroups",
                to="register_app.yeargroup",
                verbose_name="Year group",
            ),
        ),
        migrations.AddField(
            model_name="checkpointfield",
            name="checkpoint",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fields",
                to="register_app.checkpoint",
                verbose_name="Checkpoint",
            ),
        ),
        migrations.AddField(
            model_name="checkpoint",
            name="period",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="checkpoints",
                to="register_app.period",
                verbose_name="Academic period",
            ),
        ),
        migrations.AddField(
            model_name="checkpoint",
            name="teaching_classes",
            field=models.ManyToManyField(
                blank=True, related_name="checkpoints", to="register_app.teachingclass"
            ),
        ),
        migrations.AddField(
            model_name="checkpoint",
            name="yeargroups",
            field=models.ManyToManyField(
                blank=True,
                related_name="checkpoints",
                through="register_app.CheckpointYearGroup",
                to="register_app.yeargroup",
            ),
        ),
        migrations.AddConstraint(
            model_name="yeargroup",
            constraint=models.UniqueConstraint(
                fields=("level", "school"), name="unique_level"
            ),
        ),
        migrations.AddConstraint(
            model_name="yeargroup",
            constraint=models.UniqueConstraint(
                fields=("custom_name", "school"), name="unique_custom_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="teachingclass",
            constraint=models.UniqueConstraint(
                fields=("period", "name"), name="unique_teaching_class"
            ),
        ),
        migrations.AddConstraint(
            model_name="teachertag",
            constraint=models.UniqueConstraint(
                fields=("name", "school"), name="unique_student_tag"
            ),
        ),
        migrations.AddConstraint(
            model_name="studenttag",
            constraint=models.UniqueConstraint(
                fields=("name", "school"), name="unique_teacher_tag"
            ),
        ),
        migrations.AddConstraint(
            model_name="studentqualification",
            constraint=models.UniqueConstraint(
                fields=("programme", "qualification"),
                name="unique_student_qualification",
            ),
        ),
        migrations.AddConstraint(
            model_name="studentprogramme",
            constraint=models.UniqueConstraint(
                fields=("student", "name"), name="unique_student_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="period",
            constraint=models.UniqueConstraint(
                fields=("name", "school"), name="unique_period_per_school"
            ),
        ),
        migrations.AddConstraint(
            model_name="enrollmentqualification",
            constraint=models.UniqueConstraint(
                fields=("enrollment", "student_qualification"),
                name="unique_enrollment_qualification",
            ),
        ),
        migrations.AddConstraint(
            model_name="enrollment",
            constraint=models.UniqueConstraint(
                fields=("student", "period"), name="unique_student_period"
            ),
        ),
        migrations.AddConstraint(
            model_name="classenrollment",
            constraint=models.UniqueConstraint(
                fields=("enrollment_qualification", "teaching_class"),
                name="unique_class_enrollment",
            ),
        ),
        migrations.AddConstraint(
            model_name="checkpointyeargroup",
            constraint=models.UniqueConstraint(
                fields=("checkpoint", "yeargroup"), name="unique_checkpoint_yeargroup"
            ),
        ),
        migrations.AddConstraint(
            model_name="checkpointfield",
            constraint=models.UniqueConstraint(
                fields=("name", "checkpoint"), name="unique_checkpointfield_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="checkpoint",
            constraint=models.UniqueConstraint(
                fields=("name", "period"), name="unique_checkpoint_name"
            ),
        ),
    ]
