# Generated by Django 4.2.13 on 2025-01-25 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("register_app", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="checkpointyeargroup",
            name="teaching_classes",
            field=models.ManyToManyField(
                blank=True,
                related_name="checkpoint_yeargroups",
                to="register_app.teachingclass",
                verbose_name="Teaching classes",
            ),
        ),
    ]
