# Generated by Django 4.2.13 on 2025-01-25 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subject_app", "0001_initial"),
        ("register_app", "0003_checkpointyeargroup_teaching_classes"),
    ]

    operations = [
        migrations.AddField(
            model_name="checkpointyeargroup",
            name="enrollments",
            field=models.ManyToManyField(
                blank=True,
                related_name="checkpoint_yeargroups",
                to="register_app.enrollment",
                verbose_name="Enrollments",
            ),
        ),
        migrations.AddField(
            model_name="checkpointyeargroup",
            name="qualifications",
            field=models.ManyToManyField(
                blank=True,
                related_name="checkpoint_yeargroups",
                to="subject_app.qualification",
                verbose_name="Qualifications",
            ),
        ),
    ]
