# Generated by Django 4.2.13 on 2025-01-28 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("register_app", "0004_checkpointyeargroup_enrollments_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="checkpointyeargroup",
            name="class_enrollments",
            field=models.ManyToManyField(
                blank=True,
                related_name="checkpoint_yeargroups",
                to="register_app.classenrollment",
                verbose_name="Class enrollments",
            ),
        ),
        migrations.AddField(
            model_name="checkpointyeargroup",
            name="enrollment_qualifications",
            field=models.ManyToManyField(
                blank=True,
                related_name="checkpoint_yeargroups",
                to="register_app.enrollmentqualification",
                verbose_name="Enrollment qualifications",
            ),
        ),
    ]
