# Generated by Django 4.2.13 on 2025-02-02 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("register_app", "0005_checkpointyeargroup_class_enrollments_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="checkpointyeargroup",
            options={"ordering": ["checkpoint", "yeargroup"]},
        ),
    ]
