# Generated by Django 4.2.13 on 2025-02-02 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("register_app", "0006_alter_checkpointyeargroup_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="checkpointfield",
            name="checkpoint",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="checkpoint_fields",
                to="register_app.checkpoint",
                verbose_name="Checkpoint",
            ),
        ),
    ]
