# Generated by Django 5.1.5 on 2025-02-21 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("register_app", "0009_alter_checkpointfield_maxlength_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="fake",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="teacher",
            name="fake",
            field=models.BooleanField(default=False),
        ),
    ]
