# Generated by Django 5.1.5 on 2025-02-26 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("register_app", "0010_student_fake_teacher_fake"),
    ]

    operations = [
        migrations.AddField(
            model_name="period",
            name="fake",
            field=models.BooleanField(default=False),
        ),
    ]
