# IB DP & IB CP

from choices import QT, GS, Ser, SG, MT
from .ib_languages import LANGUAGE_A_LAL, LANGUAGE_A_LIT, LANGUAGE_AB, LANGUAGE_B, LANGUAGE_CLASS

QUALIFICATIONS = [
    {
        "subset": LANGUAGE_A_LIT,
        "aggregate_name": "Language A: Literature",
        "group": SG.IB.DP.LAL,
        "suffix": "A: Literature",
        "name": (QT.IB.IBO.DP.SL, QT.IB.IBO.DP.HL),
        "first_assessment": 2021,
        "last_assessment": None,
        "glh": (240, 150),
        "grading": GS.IB.SINGLE_71, 
        "series": [Ser.Exam.MAY, Ser.Exam.NOV], 
        "mark": 100,
        "mark_type": MT.SCALED,
        "modular": False,
        "current": True,
        "components": [
            {
                "name": "Paper 1: Guided literary analysis",
                "internal": False,
                "duration": ("1 hour 15 minutes", "2 hours 15 minutes"),
                "weighting": ("35%", "35%"),
                "mark": (20, 40),
                "mark_type": MT.RAW,
                "grading": GS.NONE.NAP, 
                "code": "*/1",
            },
            {
                "name": "Paper 2: Comparative essay",
                "internal": False,
                "duration": ("1 hour 45 minutes", "1 hour 45 minutes"),
                "weighting": ("35%", "25%"),
                "mark": (30, 30),
                "mark_type": MT.RAW,
                "grading": GS.NONE.NAP, 
                "code": "*/2",
            },
            {
                "name": "HL essay",
                "internal": False,
                "duration": ("1 hour 45 minutes", "1 hour 45 minutes"),
                "weighting": (None, "20%"),
                "mark": (None, 20),
                "mark_type": MT.RAW,
                "grading": GS.NONE.NAP, 
                "code": "*/3",
            },
            {
                "name": "Individual oral",
                "internal": False,
                "duration": '',
                "weighting": ("30%", "20%"),
                "mark": (40, 40),
                "mark_type": MT.RAW,
                "grading": GS.NONE.NAP, 
                "code": "*/4",
            }
        ]
    },
    {
        "subset": LANGUAGE_A_LAL,
        "aggregate_name": "Language A: Language and Literature",
        "group": SG.IB.DP.LAL,
        "suffix": "A: Language & Literature",
        "name": (QT.IB.IBO.DP.SL, QT.IB.IBO.DP.HL),
        "first_assessment": 2021,
        "last_assessment": None,
        "glh": (240, 150),
        "grading": GS.IB.SINGLE_71, 
        "mark": 100,
        "mark_type": MT.SCALED,
        "series": [Ser.Exam.MAY, Ser.Exam.NOV], 
        "modular": False,
        "current": True,
        "components": [
            {
                "name": "Paper 1: Guided textual analysis",
                "internal": False,
                "duration": ("1 hour 15 minutes", "2 hours 15 minutes"),
                "weighting": ("35%", "35%"),
                "mark": (20, 40),
                "mark_type": MT.RAW,
                "grading": GS.NONE.NAP, 
                "code": "*/1",
            },
            {
                "name": "Paper 2: Comparative essay",
                "internal": False,
                "duration": ("1 hour 45 minutes", "1 hour 45 minutes"),
                "weighting": ("35%", "25%"),
                "mark": (30, 30),
                "mark_type": MT.RAW,
                "grading": GS.NONE.NAP, 
                "code": "*/2",
            },
            {
                "name": "HL essay",
                "internal": False,
                "duration": "",
                "weighting": (None, "20%"),
                "mark": (None,20),
                "mark_type": MT.RAW,
                "grading": GS.NONE.NAP, 
                "code": "*/3",
            },
            {
                "name": "Individual oral",
                "internal": True,
                "duration": ("", ""),
                "weighting": ("30%", "20%"),
                "mark": (40, 40),
                "mark_type": MT.RAW,
                "grading": GS.NONE.NAP, 
                "code": "*/4",
            }
        ]
    },
    {
        "subject": "Literature and Performance",
        "group": SG.IB.DP.INTER,
        "code": "112845",
        "name": QT.IB.IBO.DP.SL,
        "first_assessment": 2024,
        "last_assessment": None,
        "glh": 150,
        "grading": GS.IB.SINGLE_71, 
        "mark": 100,
        "mark_type": MT.SCALED,
        "series": [Ser.Exam.MAY, Ser.Exam.NOV], 
        "modular": False,
        "current": True,
        "components": [
            {
                "name": "Paper 1",
                "internal": False,
                "duration": "1 hour 15 minutes",
                "weighting": "30%",
                "mark": 30,
                "mark_type": MT.RAW,
                "grading": GS.NONE.NAP, 
                "code": "*/1",
            },
            {
                "name": "Written assignment",
                "internal": False,
                "duration": "",
                "weighting": "30%",
                "mark": 26,
                "mark_type": MT.RAW,
                "grading": GS.NONE.NAP, 
                "code": "*/2",
            },
            {
                "name": "Transformative performance and individual oral",
                "internal": True,
                "duration": 25,
                "weighting": 40,
                "mark": 32,
                "mark_type": MT.RAW,
                "grading": GS.NONE.NAP, 
                "code": "*/3",
            }
        ]
    },
    {
        "aggregate_subject": "Classical languages",
        "group": SG.IB.DP.LA,
        "subset": LANGUAGE_CLASS,
        "name": (QT.IB.IBO.DP.SL, QT.IB.IBO.DP.HL),
        "first_assessment": 2024,
        "last_assessment": None,
        "glh": (240, 150),
        "grading": GS.IB.SINGLE_71, 
        "mark": 100,
        "mark_type": MT.SCALED,
        "series": [Ser.Exam.MAY, Ser.Exam.NOV], 
        "modular": False,
        "current": True,
        "components": [
            {
                "name": "Paper 1",
                "internal": False,
                "duration": ("1 hour 30 minutes", "2 hours"),
                "weighting": ("35%", "30%"),
                "mark": (30, 40),
                "grading": GS.NONE.NAP, 
                "code": "*/1",
            },
            {
                "name": "Paper 2: Extract questions",
                "internal": False,
                "duration": ("1 hour 30 minutes", "1 hour 30 minutes"),
                "weighting": ("35%", "30%"),
                "mark": (32, 32),
                "grading": GS.NONE.NAP, 
                "code": "*/2",
            },
            {
                "name": "HL composition",
                "internal": False,
                "duration": "",
                "weighting": (None, "20%"),
                "mark": (None, 25),
                "grading": GS.NONE.NAP, 
                "code": "*/3",
            },
            {
                "name": "Research dossier",
                "internal": True,
                "duration": "",
                "weighting": ("30%", "20%"),
                "mark": (28, 28),
                "grading": GS.NONE.NAP, 
                "code": "*/4",
            }
        ]
    },
    {
        "subset": LANGUAGE_B,
        "aggregate_subject": "Language B",
        "group": SG.IB.DP.LA,
        "suffix": "B",
        "first_assessment": 2020,
        "last_assessment": None,
        "glh": (240, 150),
        "grading": GS.IB.SINGLE_71, 
        "mark": 100,
        "mark_type": MT.SCALED,
        "series": [Ser.Exam.MAY, Ser.Exam.NOV], 
        "modular": False,
        "current": True,
        "components": [
            {
                "name": "Paper 1: Writing",
                "internal": False,
                "duration": ("1 hour 15 minutes", "1 hour 30 minutes"),
                "weighting": ("25%", "25%"),
                "mark": (30, 30),
                "grading": GS.NONE.NAP, 
                "code": "*/1",
            },
            {
                "name": "Paper 2:  Reading comprehension",
                "internal": False,
                "duration": ("1 hour 45 minutes", "2 hours"),
                "weighting": ("25%", "25%"),
                "mark": (40, 40),
                "grading": GS.NONE.NAP, 
                "code": "*/2",
            },
            {
                "name": "Paper 2:  Listening",
                "internal": False,
                "duration": ("1 hour 45 minutes", "2 hours"),
                "weighting": ("25%", "25%"),
                "mark": (25, 25),
                "grading": GS.NONE.NAP, 
                "code": "*/3",
            },
            {
                "name": "Individual Oral Assessment",
                "internal": False,
                "duration": "",
                "weighting": ("25%", "25%"),
                "mark": (30, 30),
                "grading": GS.NONE.NAP, 
                "code": "*/4",
            }
        ]
    },
    {
        "subset": LANGUAGE_AB,
        "aggregate_subject": "Literature Ab Initio",
        "group": SG.IB.DP.LA,
        "suffix": "Ab Initio",
        "name": QT.IB.IBO.DP.SL,
        "first_assessment": 2024,
        "last_assessment": None,
        "glh": 150,
        "grading": GS.IB.SINGLE_71, 
        "mark": 100,
        "mark_type": MT.SCALED,
        "series": [Ser.Exam.MAY, Ser.Exam.NOV], 
        "modular": False,
        "current": True,
        "components": [
            {
                "name": "Paper 1: Writing",
                "internal": False,
                "duration": "1 hour",
                "weighting": "25%",
                "mark": 30,
                "grading": GS.NONE.NAP, 
                "code": "*/1",
            },
            {
                "name": "Paper 2: Reading Comprehension",
                "internal": False,
                "duration": "1 hour 45 minutes",
                "weighting": "25%",
                "mark": 40,
                "notes": "Duration applies to the entire Paper 2 (reading & listening)",
                "code": "*/2A",
                "grading": GS.NONE.NAP, 
            },
            {
                "name": "Paper 2: Listening",
                "internal": False,
                "duration": "1 hour 45 minutes",
                "weighting": "25%",
                "mark": 25,
                "notes": "Duration applies to the entire Paper 2 (reading & listening)",
                "code": "*/2B",
                "grading": GS.NONE.NAP, 
            },
            {
                "name": "Individual Oral Assessment",
                "internal": True,
                "duration": "",
                "weighting": "25%",
                "mark": 30,
                "code": "*/3",
                "grading": GS.NONE.NAP, 
            }
        ]
    },
    {
        "subject": "Biology",
        "group": SG.IB.DP.SCIENCES,
        "code": "100058",
        "name": (QT.IB.IBO.DP.SL, QT.IB.IBO.DP.HL),
        "first_assessment": 2016,
        "last_assessment": 2024,
        "glh": (240, 150),
        "grading": GS.IB.SINGLE_71, 
        "mark": 100,
        "mark_type": MT.SCALED,
        "series": [Ser.Exam.MAY, Ser.Exam.NOV], 
        "modular": False,
        "current": False,
        "components": [
            {
                "name": "Paper 1: Multiple Choice",
                "internal": False,
                "duration": ("45 minutes", "45 minutes"),
                "weighting": ("20%", "20%"),
                "mark": (30, 40),
                "code": "*/1",
                "grading": GS.NONE.NAP, 
            },
            {
                "name": "Paper 2: Data-Based",
                "internal": False,
                "duration": ("1 hour 15 minutes", "1 hour 15 minutes"),
                "weighting": ("40%", "40%"),
                "mark": (50, 72),
                "code": "*/2",
                "grading": GS.NONE.NAP, 
            },
            {
                "name": "Paper 3",
                "internal": False,
                "duration": ("1 hour", "1 hour"),
                "weighting": ("35%", "45%"),
                "mark": (24, 24),
                "code": "*/3",
                "grading": GS.NONE.NAP, 
            },
            {
                "name": "Individual investigation",
                "internal": True,
                "duration": "",
                "weighting": ("20%", "20%"),
                "mark": (24, 24),
                "code": "*/4",
                "grading": GS.NONE.NAP, 
            }
        ]
    },
    {
        "subject": "Biology",
        "group": SG.IB.DP.SCIENCES,
        "code": "100058",
        "name": (QT.IB.IBO.DP.SL, QT.IB.IBO.DP.HL),
        "first_assessment": 2025,
        "last_assessment": None,
        "glh": (240, 150),
        "grading": GS.IB.SINGLE_71, 
        "mark": 100,
        "mark_type": MT.SCALED,
        "series": [Ser.Exam.MAY, Ser.Exam.NOV], 
        "modular": False,
        "current": True,
        "components": [
            {
                "name": "Paper 1: Multiple choice & Data-based",
                "internal": False,
                "duration": ("1 hour 30 minutes", "2 hours"),
                "weighting": "36%",
                "mark": (0, 0),
                "code": "*/1",
                "grading": GS.IB.SINGLE_71, 
            },
            {
                "name": "Paper 2: Data-based & extended response",
                "internal": False,
                "duration": ("1 hour 30 minutes", "2 hours 30 minutes"),
                "weighting": "44%",
                "mark": (0, 0),
                "code": "*/2",
                "grading": GS.NONE.NAP, 
            },
            {
                "name": "Scientific investigation",
                "internal": True,
                "duration": "",
                "weighting": "20%",
                "mark": (24, 24),
                "code": "*/3",
                "grading": GS.NONE.NAP, 
            }
        ]
    },
    {
        "subject": "Art history",
        "group": SG.IB.DP.INDIV_SOC,
        "code": "100058",
        "name": QT.IB.IBO.DP.SL,
        "first_assessment": 2024,
        "last_assessment": None,
        "glh": (240, 150),
        "sbs": True,
        "grading": GS.IB.SINGLE_71, 
        "mark": 100,
        "mark_type": MT.SCALED,
        "series": [Ser.Exam.MAY, Ser.Exam.NOV], 
        "modular": False,
        "components": [
            {
                "name": "Paper 1: Short Answer",
                "internal": False,
                "duration": "",
                "weighting": "20%",
                "mark": 20,
                "code": "*/1",
                "grading": GS.NONE.NAP, 
            },
            {
                "name": "Paper 2: Extended Response",
                "internal": False,
                "duration": "",
                "weighting": "48%",
                "mark": 48,
                "code": "*/2",
                "grading": GS.NONE.NAP, 
            },
            {
                "name": "Internal Assessment",
                "internal": True,
                "duration": "",
                "weighting": "32%",
                "mark": 32,
                "code": "*/3",
                "grading": GS.NONE.NAP, 
            }
        ]
    },
    {
        "subject": "History",
        "group": SG.IB.DP.INDIV_SOC,
        "code": "100680",
        "name": QT.IB.IBO.DP.SL,
        "first_assessment": 2017,
        "last_assessment": None,
        "glh": 150,
        "grading": GS.IB.SINGLE_71, 
        "mark": 100,
        "mark_type": MT.SCALED,
        "series": [Ser.Exam.MAY, Ser.Exam.NOV], 
        "modular": False,
        "components": [
            {
                "name": "Paper 1: Source-based",
                "internal": False,
                "duration": "1 hour",
                "weighting": "30%",
                "mark": 24,
                "code": "*/1",
                "grading": GS.NONE.NAP, 
            },
            {
                "name": "Paper 2: Essay",
                "internal": False,
                "duration": "1 hour 30 minutes",
                "weighting": "45%",
                "mark": 24,
                "code": "*/2",
                "grading": GS.NONE.NAP, 
            },
            {
                "name": "Historical investigation",
                "internal": True,
                "duration": "20 hours",
                "weighting": "25%",
                "mark": 25,
                "code": "*/3",
                "grading": GS.NONE.NAP, 
            }
        ]
    },
    {
        "subject": (
            "History - Africa and the Middle East",
            "History - Americas",
            "History - Asia and Oceania",
            "History - Europe",
        ),
        "group": SG.IB.DP.INDIV_SOC,
        "code": (
            "149713",
            "149711",
            "149714",
            "149712",
        ),
        "name": QT.IB.IBO.DP.HL,
        "first_assessment": 2017,
        "last_assessment": None,
        "glh": 240,
        "grading": GS.IB.SINGLE_71, 
        "mark": 100,
        "mark_type": MT.SCALED,
        "series": [Ser.Exam.MAY, Ser.Exam.NOV], 
        "modular": False,
        "components": [
            {
                "name": "Paper 1: Source-based",
                "internal": False,
                "duration": "1 hour",
                "weighting": "20%",
                "mark": 24,
                "code": "*/1",
                "grading": GS.NONE.NAP, 
            },
            {
                "name": "Paper 2: Essay (World history)",
                "internal": False,
                "duration": "1 hour 30 minutes",
                "weighting": "25%",
                "mark": 24,
                "code": "*/2",
                "grading": GS.NONE.NAP, 
            },
            {
                "name": "Paper 3: Essay (Regional history)",
                "internal": False,
                "duration": "2 hours 30 minutes",
                "weighting": 35,
                "mark": 45,
                "code": "*/3",
                "grading": GS.NONE.NAP, 
            },
            {
                "name": "Historical investigation",
                "internal": True,
                "duration": "20 hours",
                "weighting": "20%",
                "mark": 25,
                "code": "*/4",
                "grading": GS.NONE.NAP, 
            }
        ]
    },
    {
        "subject": "Theory of Knowledge",
        "group": SG.IB.DP.CORE,
        "name": QT.IB.IBO.DP.CORE,
        "first_assessment": 2022,
        "last_assessment": None,
        "glh": 100,
        "grading": GS.IB.SINGLE_AE, 
        "mark": 100,
        "mark_type": MT.SCALED,
        "series": [Ser.Exam.MAY, Ser.Exam.NOV], 
        "modular": False,
        "core": True,
        "code": "TOK",
        "components": [
            {
                "name": "Theory Of Knowledge Essay",
                "internal": False,
                "duration": "",
                "weighting": "67%",
                "mark": 10,
                "code": "*/1",
                "grading": GS.IB.SINGLE_AE, 
            },
            {
                "name": "Theory Of Knowledge Exhibition",
                "internal": False,
                "duration": "",
                "weighting": "33%",
                "mark": 10,
                "code": "*/2",
                "grading": GS.IB.SINGLE_AE, 
            },
        ]
    },
    
    {
        "subject": "Extended Essay",
        "group": SG.IB.DP.CORE,
        "name": QT.IB.IBO.DP.CORE,
        "first_assessment": 2018,
        "last_assessment": None,
        "glh": 0,
        "grading": GS.IB.SINGLE_AE, 
        "series": [Ser.Exam.MAY, Ser.Exam.NOV], 
        "mark": 100,
        "mark_type": MT.SCALED,
        "modular": False,
        "core": True,
        "code": "EE",
        "components": [
            {
                "name": "Extended Essay",
                "internal": False,
                "duration": "40 hours",
                "weighting": "100%",
                "mark": 34,
                "code": "*/1",
                "grading": GS.IB.SINGLE_AE, 
            },
        ]
    },

    {
        "subject": "Reflective project",
        "code": "100657",
        "group": SG.IB.CP.CORE,
        "name": QT.IB.IBO.CP.CORE,
        "glh": 0,
        "first_assessment": 2016,
        "last_assessment": None,
        "grading": GS.IB.SINGLE_AE, 
        "series": [Ser.Exam.MAY, Ser.Exam.NOV], 
        "mark": 100,
        "mark_type": MT.SCALED,
        "modular": False,
        "core": True,
        "components": [
            {
                "name": "Reflective project",
                "internal": False,
                "duration": "50 hours",
                "weighting": "100%",
                "mark": 36,
                "code": "*/1",
                "grading": GS.IB.SINGLE_AE, 
            },
        ]
    },
    {
        "subject": "Core points matrix",
        "code": "IBDP-CPM",
        "group": SG.IB.DP.CORE,
        "name": QT.IB.IBO.DP.AGG,
        "glh": 0,
        "first_assessment": 2016,
        "last_assessment": None,
        "grading": GS.IB.SINGLE_31, 
        "series": [Ser.Exam.MAY, Ser.Exam.NOV], 
        "mark": None,
        "mark_type": MT.NONE,
        "modular": False,
        "aggregate": True,
        "components": []
    },
    {
        "subject": "Diploma",
        "code": "IBDP-DP",
        "group": SG.IB.DP.CORE,
        "name": QT.IB.IBO.DP.AGG,
        "glh": 400,
        "first_assessment": 2016,
        "last_assessment": None,
        "grading": GS.IB.PASS_FAIL, 
        "series": [Ser.Exam.MAY, Ser.Exam.NOV], 
        "mark": 45,
        "mark_type": MT.POINTS,
        "modular": False,
        "aggregate": True,
        "mark_required": True,
        "components": []
    },
    {
        "subject": "Creativity, activity, service (CAS)",
        "code": "IBDP-CAS",
        "group": SG.IB.DP.CORE,
        "name": QT.IB.IBO.DP.CORE,
        "glh": 0,
        "first_assessment": 2016,
        "last_assessment": None,
        "grading": GS.IB.PASS_FAIL, 
        "series": [Ser.Exam.MAY, Ser.Exam.NOV], 
        "mark": None,
        "mark_type": MT.NONE,
        "modular": False,
        "core": True,
        "components": []
    }
]

