from choices import QT, GS, Ser, SG, MT

QUALIFICATIONS = [
        {
        'subject': 'Art and Design',
        'code': (
            'BTI3ART/SD',
            'BTI3ART/FD',
            'BTI3ART/D',
            'BTI3ART/ED',
        ),
        'group': SG.UK.PROFESSIONAL,
        
        'name': (
            QT.UKI.BTEC.IL3.SUB_DIP,
            QT.UKI.BTEC.IL3.FDN_DIP,
            QT.UKI.BTEC.IL3.DIP,
            QT.UKI.BTEC.IL3.EXT_DIP,
        ),

        'glh': (360, 540, 720, 1080),
        'first_assessment': 2020,
        'last_assessment': None,
        'current': True,
        'mark': (45, 45, 60, 120),
        'mark_type': MT.POINTS,
        'grading': (
            GS.AGQ.SINGLE_DSP,
            GS.AGQ.SINGLE_DP,
            GS.AGQ.DOUBLE_DSP,
            GS.AGQ.TRIPLE_DSP,
        ), 
        'series': [Ser.Flex.ALL],
        'modular': False, 
        'components': [
            {
                'name': 'A1 Skills Development',
                'code': '*/A1',
                'mark': None,
                'mark_type': MT.POINTS,
                'glh': 270,
                'weighting': ('glh', 'glh', 'glh', 'glh'),
                'grading': GS.AGQ.SINGLE_DP,
                'internal': True,
                'optional': False,
            },
            {
                'name': 'A2 Responding to a Brief (PSA)',
                'code': '*/A2',
                'mark': None,
                'mark_type': MT.POINTS,
                'glh': 90,
                'weighting': ('glh', 'glh', 'glh', 'glh'),
                'grading': GS.AGQ.SINGLE_DP,
                'internal': True,
                'optional': False,
            },
            {
                'name': 'A3 Creative Project',
                'code': '*/A3',
                'mark': None,
                'mark_type': MT.POINTS,
                'glh': 180,
                'weighting': (None, 'glh', None, 'glh'),
                'grading': GS.AGQ.SINGLE_DP,
                'internal': True,
                'optional': False,
            },
            {
                'name': 'B1 Personal Progression',
                'code': '*/A3',
                'mark': None,
                'mark_type': MT.POINTS,
                'glh': 90,
                'weighting': (None, None, 'glh', 'glh'),
                'grading': GS.AGQ.SINGLE_DP,
                'internal': True,
                'optional': False,
            },
            {
                'name': 'B2 Personal Investigation (PSA)',
                'code': '*/A3',
                'mark': None,
                'mark_type': MT.POINTS,
                'glh': 90,
                'weighting': (None, None, None, 'glh'),
                'grading': GS.AGQ.SINGLE_DP,
                'internal': True,
                'optional': False,
            },
            {
                'name': 'B3 Creative Industry Response',
                'code': '*/A3',
                'mark': None,
                'mark_type': MT.POINTS,
                'glh': 270,
                'weighting': (None, None, 'glh', None),
                'grading': GS.AGQ.SINGLE_DP,
                'internal': True,
                'optional': False,
            },
            {
                'name': 'B4 Extended Creative Industry Response',
                'code': '*/A3',
                'mark': None,
                'mark_type': MT.POINTS,
                'glh': 360,
                'weighting': (None, None, None, 'glh'),
                'grading': GS.AGQ.SINGLE_DP,
                'internal': True,
                'optional': False,
            },
        ]
    },
]