from choices import QT, GS, Ser, SG, MT

QUALIFICATIONS = [
        {
        'subject': (
            'Engineering',
            'Engineering',
            'Engineering', 'Mechatronics', 'Vehicle Technology',
            'Engineering', 'Mechatronics', 'Vehicle Technology',
        ),
        'code': (
            'BTI2EN/A',
            'BTI2EN/C',
            'BTI2EN/EC', 'BTI2ME/EC', 'BTI2VT/EC',
            'BTI2EN/D', 'BTI2ME/D', 'BTI2VT/D',
        ),
        'group': SG.UK.PROFESSIONAL,
        'name': (
            QT.UKI.BTEC.IL2.AWARD,
            QT.UKI.BTEC.IL2.CERT,
            QT.UKI.BTEC.IL2.EXT_CERT, QT.UKI.BTEC.IL2.EXT_CERT, QT.UKI.BTEC.IL2.EXT_CERT,
            QT.UKI.BTEC.IL2.DIP, QT.UKI.BTEC.IL2.DIP, QT.UKI.BTEC.IL2.DIP,
        ),

        'glh': (120, 
                240, 
                360, 360, 360,
                480, 480, 480,
        ),
        'first_assessment': 2022,
        'last_assessment': None,
        'current': True,
        'mark': (
            96, 
            192, 
            288, 288, 288,
            384, 384, 384,
        ),
        'mark_type': MT.POINTS,
        'grading': (
            GS.AGQ.SINGLE_DSP,
            GS.AGQ.DOUBLE_DSP,
            GS.AGQ.DOUBLE_DSP, GS.AGQ.DOUBLE_DSP, GS.AGQ.DOUBLE_DSP,
            GS.AGQ.DOUBLE_DSP, GS.AGQ.DOUBLE_DSP, GS.AGQ.DOUBLE_DSP,
        ), 
        'series': [Ser.Flex.ALL],
        'modular': False, 
        'components': [
            {
                'name': 'Unit 1: Working Safely and Effectively in Engineering',
                'code': '*/01',
                'mark': None,
                'mark_type': MT.NONE,
                'glh': 30,
                'weighting': 'glh',  
                'grading': GS.AGQ.SINGLE_DP,
                'internal': True,
                'optional': False, 
            },
            {
                'name': 'Unit 2: Engineering Thinking Skills to Create Solutions',
                'code': '*/02',
                'mark': None,
                'mark_type': MT.NONE,
                'glh': 30,
                'weighting': 'glh',
                'grading': GS.AGQ.SINGLE_DP,
                'internal': True,
                'optional': False,
            },
            {
                'name': 'Unit 3: Investigating an Engineering Product',
                'code': '*/03',
                'mark': None,
                'mark_type': MT.NONE,
                'glh': 30,
                'weighting': 'glh',
                'grading': GS.AGQ.SINGLE_DP,
                'internal': True,
                'optional': (
                    True,
                    False,
                    False, False, False,
                    False, False, False,
                ),
            },
            {
                'name': 'Unit 4: Engineering Maintenance',
                'code': '*/04',
                'mark': None,
                'mark_type': MT.NONE,
                'glh': 30,
                'weighting': 'glh',
                'grading': GS.AGQ.SINGLE_DP,
                'internal': True,
                'optional': (
                    True,
                    True,
                    False, False, False,
                    False, False, False,
                ),  
            },
            {
                'name': 'Unit 5: Mathematics for Engineering Technicians',
                'code': '*/05',
                'mark': None,
                'mark_type': MT.NONE,
                'glh': 30,
                'weighting': 'glh',
                'grading': GS.AGQ.SINGLE_DP,
                'internal': True,
                'optional': (
                    True,
                    True,
                    True, True, True,
                    False, False, False,
                ),
            },
            {
            'name': 'Unit 6:  Engineering Materials',
            'code': '*/06',
            'mark': None,
            'mark_type': MT.NONE,
            'glh': 30,
            'weighting': 'glh',
            'grading': GS.AGQ.SINGLE_DP,
            'internal': True,
            'optional': True,    
            },
            {
                'name': 'Unit 7: Engineering Drawing',
                'code': '*/07',
                'mark': None,
                'mark_type': MT.NONE,
                'glh': 60,
                'weighting': 'glh',
                'grading': GS.AGQ.SINGLE_DP,
                'internal': True,
                'optional': True,    
            },

            {
                'name': 'Unit 8: Machining Techniques',
                'code': '*/08',
                'mark': None,
                'mark_type': MT.NONE,
                'glh': 60,
                'weighting': 'glh',
                'grading': GS.AGQ.SINGLE_DP,
                'internal': True,
                'optional': True,
            },
            {
                'name': 'Unit 9: Engineering Design',
                'code': '*/09',
                'mark': None,
                'mark_type': MT.NONE,
                'glh': 60,
                'weighting': 'glh',
                'grading': GS.AGQ.SINGLE_DP,
                'internal': True,
                'optional': True,
            },
            {
                'name': 'Unit 10: Engineering Fitting and Assembly',
                'code': '*/10',
                'mark': None,
                'mark_type': MT.NONE,
                'glh': 30,
                'weighting': 'glh',
                'grading': GS.AGQ.SINGLE_DP,
                'internal': True,
                'optional': True,
            },
            {
                'name': 'Unit 11: Welding',
                'code': '*/11',
                'mark': None,
                'mark_type': MT.NONE,
                'glh': 60,
                'weighting': (
                    None, 
                    None, 
                    'glh', 'glh', 'glh', 
                    'glh', 'glh', 'glh'
                ),
                'grading': GS.AGQ.SINGLE_DP,
                'internal': True,
                'optional': True,
            },
            {
                'name': 'Unit 12: Business Improvement Techniques',
                'code': '*/13',
                'mark': None,
                'mark_type': MT.NONE,
                'glh': 60,
                'weighting': 'glh',
                'grading': GS.AGQ.SINGLE_DP,
                'internal': True,
                'optional': True,
            },
            {
                'name': 'Unit 13: Operations and Maintenance of Mechanical Systems and Components',
                'code': '*/13',
                'mark': None,
                'mark_type': MT.NONE,
                'glh': 60,
                'weighting': (
                    None, 
                    'glh', 
                    'glh', 'glh', 'glh', 
                    'glh', 'glh', 'glh'
                ),
                'grading': GS.AGQ.SINGLE_DP,
                'internal': True,
                'optional': True,
            },
            {
                'name': 'Unit 14: Fabrication Techniques',
                'code': '*/13',
                'mark': None,
                'mark_type': MT.NONE,
                'glh': 60,
                'weighting': (
                    'glh', 
                    'glh', 
                    'glh', None, None, 
                    'glh', None, None, 
                ),
                'grading': GS.AGQ.SINGLE_DP,
                'internal': True,
                'optional': True,
            },
            {
                'name': 'Unit 15: Engineering Marking Out',
                'code': '*/13',
                'mark': None,
                'mark_type': MT.NONE,
                'glh': 30,
                'weighting': (
                    'glh', 
                    'glh', 
                    'glh', None, None, 
                    'glh', None, None, 
                ),
                'grading': GS.AGQ.SINGLE_DP,
                'internal': True,
                'optional': True,
            },
            {
                'name': 'Unit 16: Application of Quality Control and Measurement in Engineering',
                'code': '*/16',
                'mark': None,
                'mark_type': MT.NONE,
                'glh': 60,
                'weighting': 'glh',
                'grading': GS.AGQ.SINGLE_DP,
                'internal': True,
                'optional': True,
            },
            {
                'name': 'Unit 17: 3D Printing',
                'code': '*/17',
                'mark': None,
                'mark_type': MT.NONE,
                'glh': 60,
                'weighting': 'glh',
                'grading': GS.AGQ.SINGLE_DP,
                'internal': True,
                'optional': True,
            },
            {
                'name': 'Unit 18: Applied Chemistry for Engineers',
                'code': '*/18',
                'mark': None,
                'mark_type': MT.NONE,
                'glh': 30,
                'weighting': (
                    None, 
                    None, 
                    'glh', 'glh', 'glh', 
                    'glh', 'glh', 'glh'
                ),
                'grading': GS.AGQ.SINGLE_DP,
                'internal': True,
                'optional': True,
            },
            {
                'name': 'Unit 19: Data Capture and Interpretation',
                'code': '*/19',
                'mark': None,
                'mark_type': MT.NONE,
                'glh': 60,
                'weighting': (
                    None, 
                    'glh', 
                    'glh', 'glh', 'glh', 
                    'glh', 'glh', 'glh'
                ),
                'grading': GS.AGQ.SINGLE_DP,
                'internal': True,
                'optional': True,
            },
            {
                'name': 'Unit 20: Electrical and Mechanical Science for Engineering',
                'code': '*/20',
                'mark': None,
                'mark_type': MT.NONE,
                'glh': 30,
                'weighting': 'glh',
                'grading': GS.AGQ.SINGLE_DP,
                'internal': True,
                'optional': True,
            },
            {
                'name': 'Unit 21: Renewable Technologies and Sustainability',
                'code': '*/21',
                'mark': None,
                'mark_type': MT.NONE,
                'glh': 60,
                'weighting': 'glh',
                'grading': GS.AGQ.SINGLE_DP,
                'internal': True,
                'optional': True,
            },
            {
                'name': 'Unit 22: Electrical and Electronic Circuit Construction and Testing',
                'code': '*/22',
                'mark': None,
                'mark_type': MT.NONE,
                'glh': 60,
                'weighting': 'glh',
                'grading': GS.AGQ.SINGLE_DP,
                'internal': True,
                'optional': True,
            },
            {
                'name': 'Unit 23: Electronic Devices and Communication Applications',
                'code': '*/23',
                'mark': None,
                'mark_type': MT.NONE,
                'glh': 60,
                'weighting': 'glh',
                'grading': GS.AGQ.SINGLE_DP,
                'internal': True,
                'optional': True,
            },
            {
                'name': 'Unit 24: Operation and Maintenance of Electrical and Electronic Systems and Components',
                'code': '*/24',
                'mark': None,
                'mark_type': MT.NONE,
                'glh': 60,
                'weighting': 'glh',
                'grading': GS.AGQ.SINGLE_DP,
                'internal': True,
                'optional': (
                    True,
                    True,
                    True, False, True,
                    True, False, True,
                ),
            },
            {
                'name': 'Unit 25: Computer Numerical Control Programming and Machining',
                'code': '*/25',
                'mark': None,
                'mark_type': MT.NONE,
                'glh': 60,
                'weighting': 'glh',
                'grading': GS.AGQ.SINGLE_DP,
                'internal': True,
                'optional': True,
            },
            {
                'name': 'Unit 26: Robotics',
                'code': '*/26',
                'mark': None,
                'mark_type': MT.NONE,
                'glh': 60,
                'weighting': 'glh',
                'grading': GS.AGQ.SINGLE_DP,
                'internal': True,
                'optional': True,
            },
            {
                'name': 'Unit 27: General Programming',
                'code': '*/27',
                'mark': None,
                'mark_type': MT.NONE,
                'glh': 60,
                'weighting': 'glh',
                'grading': GS.AGQ.SINGLE_DP,
                'internal': True,
                'optional': True,
            },
            {
                'name': 'Unit 28: Automated Systems',
                'code': '*/28',
                'mark': None,
                'mark_type': MT.NONE,
                'glh': 60,
                'weighting': 'glh',
                'grading': GS.AGQ.SINGLE_DP,
                'internal': True,
                'optional': (
                    True,
                    True,
                    True, False, True,
                    True, False, True,
                ),
            },
            {
                'name': 'Unit 29: Cyber Security in Engineering',
                'code': '*/29',
                'mark': None,
                'mark_type': MT.NONE,
                'glh': 30,
                'weighting': (
                    None, 
                    'glh', 
                    'glh', 'glh', 'glh', 
                    'glh', 'glh', 'glh'
                ),
                'grading': GS.AGQ.SINGLE_DP,
                'internal': True,
                'optional': True,
            },
            {
                'name': 'Unit 30: Sustainable Vehicle Power and Structure Design',
                'code': '*/30',
                'mark': None,
                'mark_type': MT.NONE,
                'glh': 60,
                'weighting': (
                    None, 
                    None, 
                    None, None, 'glh', 
                    None, None, 'glh', 
                ),
                'grading': GS.AGQ.SINGLE_DP,
                'internal': True,
                'optional': True,
            },
            {
                'name': 'Unit 31: Vehicle Maintenance Techniques',
                'code': '*/31',
                'mark': None,
                'mark_type': MT.NONE,
                'glh': 60,
                'optional': True,
                'grading': GS.AGQ.SINGLE_DP,
                'internal': True,
                'weighting': (
                    None, 
                    'glh', 
                    'glh', 'glh', 'glh', 
                    'glh', 'glh', 'glh'
                ),
            },
            {
                'name': 'Unit 32: Vehicle Engine Technology',
                'code': '*/32',
                'mark': None,
                'mark_type': MT.NONE,
                'glh': 60,
                'weighting': (
                    None, 
                    None, 
                    'glh', None, 'glh', 
                    'glh', None, 'glh', 
                ),
                'grading': GS.AGQ.SINGLE_DP,
                'internal': True,
                'optional': True,
            },
            {
                'name': 'Unit 33: Vehicle Electrical and Electronic Systems',
                'code': '*/33',
                'mark': None,
                'mark_type': MT.NONE,
                'glh': 60,
                'grading': GS.AGQ.SINGLE_DP,
                'internal': True,
                'weighting': (
                    None, 
                    None, 
                    None, 'glh', 'glh', 
                    None, 'glh', 'glh', 
                ),
                'optional': True,
            },
            {
                'name': 'Unit 34: Hybrid and Electric Vehicles',
                'code': '*/34',
                'mark': None,
                'mark_type': MT.NONE,
                'glh': 60,
                'optional': True,
                'grading': GS.AGQ.SINGLE_DP,
                'internal': True,
                'weighting': (
                    None, 
                    None, 
                    None, None, 'glh', 
                    None, None, 'glh', 
                ),
            },
        ]
    },
]